@file:OptIn(com.transfer.flash.core.common.annotation.FlashInternalApi::class)

package com.transfer.flash.debug

import android.content.Context
import android.util.Log
import com.transfer.flash.core.common.model.FlashDeviceId
import com.transfer.flash.core.common.protocol.FlashTextFraming
import com.transfer.flash.core.discovery.core.CompositeDiscovery
import com.transfer.flash.core.discovery.core.FlashAdvertisedIdentity
import com.transfer.flash.core.discovery.core.FlashDiscoveryMode
import com.transfer.flash.core.messaging.FlashChatRepository
import com.transfer.flash.core.messaging.RealFlashChatRepository
import com.transfer.flash.core.messaging.protocol.MessageWireFrame
import com.transfer.flash.core.network.FlashNetwork
import com.transfer.flash.core.network.bridge.DiscoveryRouteBinder
import com.transfer.flash.core.network.ws.WsFlashNetwork
import com.transfer.flash.core.network.ws.WsSession
import com.transfer.flash.core.transfer.FlashTransferRepository
import com.transfer.flash.core.transfer.RealFlashTransferRepository
import com.transfer.flash.core.transfer.chunked.ChunkFrame
import com.transfer.flash.core.transfer.chunked.ReceiveEvent
import com.transfer.flash.core.transfer.chunked.ReceivePipeline
import com.transfer.flash.core.transfer.multistream.StreamChannel
import com.transfer.flash.core.transfer.policy.FileRandomAccessSinkHandle
import com.transfer.flash.core.transfer.policy.RandomAccessChunkSink
import com.transfer.flash.core.transfer.policy.RandomAccessSinkHandle
import com.transfer.flash.core.common.result.FlashResult
import com.transfer.flash.identity.AppIdentity
import java.io.File
import java.io.IOException
import java.io.InputStream
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock

/**
 * Process-wide engine holder for the debug Dev Console and background service.
 *
 * Utilizes [WsFlashNetwork] as the full-duplex WebSocket mesh network layer,
 * wired to [RealFlashChatRepository] for instant messaging and [RealFlashTransferRepository]
 * with [ReceivePipeline] for chunked binary file transfers.
 *
 * Received files land at `<external-files>/FlashReceived/<transferId>/<safeFileName>` written
 * via random-access handles at exact chunk offsets (`index * chunkSize`), which is REQUIRED
 * for correct out-of-order multi-stream assembly (ADR-015).
 */
object DiscoveryEngineHolder {

    private const val TAG_DISCOVERY = "DISCOVERY"
    private const val TAG_TRANSFER = "TRANSFER"
    private const val TAG_CHAT = "CHAT"
    private const val TAG_WS = "WS"

    /** Explicit Dev Console test payload URI — intentionally streams generated bytes. */
    private const val TEST_PAYLOAD_URI = "file:///dummy/test_payload.bin"

    private const val MSG_PREFIX = "FLASH_MSG"
    private const val RECEIPT_PREFIX = "FLASH_RCPT"
    private const val XFER_PREFIX = "FLASH_XFER"

    @Volatile
    private var composite: CompositeDiscovery? = null

    @Volatile
    private var network: WsFlashNetwork? = null

    @Volatile
    private var transferRepo: FlashTransferRepository? = null

    @Volatile
    private var chatRepo: FlashChatRepository? = null

    @Volatile
    private var dataServer: com.transfer.flash.core.network.datachannel.DataChannelServer? = null

    private var binderJob: Job? = null

    private val appScope = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    /** Serializes start/stop so racing callers cannot leak duplicate NSD engines/servers. */
    private val lifecycleMutex = Mutex()

    fun current(): CompositeDiscovery? = composite

    fun currentNetwork(): FlashNetwork? = network

    fun currentTransfers(): FlashTransferRepository? = transferRepo

    fun currentChats(): FlashChatRepository? = chatRepo

    suspend fun ensureStarted(context: Context): CompositeDiscovery = lifecycleMutex.withLock {
        composite?.let { return it }
        val appContext = context.applicationContext
        val identity0 = AppIdentity(appContext)
        val identity = FlashAdvertisedIdentity(
            deviceId = FlashDeviceId(
                value = identity0.deviceId.ifBlank { UUID.randomUUID().toString() },
            ),
            friendlyName = identity0.friendlyName.ifBlank { "Flash Device" },
            deviceModel = android.os.Build.MODEL ?: "unknown",
            protocolVersion = 2,
        )

        Log.i(TAG_DISCOVERY, "Starting Flash discovery with deviceId=${identity.deviceId.value} friendlyName=${identity.friendlyName}")

        val transport = com.transfer.flash.core.discovery.nsd.NsdTransport(
            context = appContext,
            apiLevel = com.transfer.flash.core.discovery.nsd.BuildNsdApiLevel,
            directory = com.transfer.flash.core.discovery.core.StandardEndpointDirectory(),
            sweep = { _ -> emptyList() },
        )
        val engine = CompositeDiscovery(transports = listOf(transport))

        val networkImpl = WsFlashNetwork(
            context = appContext,
            localDeviceId = identity.deviceId.value,
            localFriendlyName = identity.friendlyName,
        )
        binderJob = DiscoveryRouteBinder.observe(appScope, engine.discoveredEndpoints, networkImpl)

        // Start WebSocket network server
        val netStartResult = networkImpl.start(0)
        val serverPort = (netStartResult as? FlashResult.Success)?.value ?: 0
        check(serverPort > 0) { "Network server failed to start: ${(netStartResult as? FlashResult.Failure)?.error}" }

        Log.i(TAG_WS, "WsFlashNetwork server listening on port=$serverPort")

        engine.setMode(FlashDiscoveryMode.STANDARD)
        val result = engine.startAll(serverPort, identity)
        check(result.isSuccess) {
            "Discovery startAll failed: ${(result as? FlashResult.Failure)?.error}"
        }

        val db = androidx.room.Room.databaseBuilder(
            appContext,
            com.transfer.flash.core.persistence.db.FlashDatabase::class.java,
            "flash-dev.db",
        ).fallbackToDestructiveMigration(dropAllTables = true).build()

        // ---- receive-side infrastructure (must precede the send factory wiring) ----
        val receivedDir = File(appContext.getExternalFilesDir(null), "FlashReceived").apply { mkdirs() }
        val openHandles = ConcurrentHashMap<String, RandomAccessSinkHandle>()
        val incomingMeta = ConcurrentHashMap<String, ChunkFrame.FileStart>()

        /** Per-peer resolved data-port offset from its advertised WS port (probed once). */
        val dataPortCache = ConcurrentHashMap<String, Int>()

        val receivePipeline = ReceivePipeline(
            sink = { _, _ -> Log.w(TAG_TRANSFER, "Legacy shared sink invoked — expected per-transfer sinkFactory") },
            sinkFactory = { start ->
                val safeName = sanitizePathComponent(start.fileName.ifBlank { "received.bin" })
                val safeId = sanitizePathComponent(start.transferId)
                val dest = File(File(receivedDir, safeId), safeName)
                dest.parentFile?.mkdirs()
                val handle = FileRandomAccessSinkHandle(dest, start.totalBytes)
                openHandles[start.transferId] = handle
                Log.i(TAG_TRANSFER, "Receiver destination opened file=${dest.absolutePath} totalBytes=${start.totalBytes} chunkSize=${start.chunkSize}")
                RandomAccessChunkSink(handle, start.chunkSize)
            },
            emitSessionStarted = true,
        )

        // Real N-socket multistream: dedicated plain-TCP data channels next to the WS port.
        val router = DataChannelRouter(receivePipeline, openHandles, incomingMeta)
        val dcServer = com.transfer.flash.core.network.datachannel.DataChannelServer(
            localDeviceId = identity.deviceId.value,
            listener = object : com.transfer.flash.core.network.datachannel.DataChannelServer.Listener {
                override fun onFrame(
                    senderDeviceId: String,
                    channelId: Int,
                    payload: ByteArray,
                    reply: (ByteArray) -> Boolean,
                ) {
                    router.onBytes("dc:$channelId", senderDeviceId, payload, reply)
                }

                override fun onConnectionClosed(peerDeviceId: String?, channelId: Int) = Unit
            },
        )
        val dataPort = runCatching {
            dcServer.start(preferredPort = serverPort + 1)
        }.getOrElse {
            Log.w(TAG_WS, "DataChannelServer failed to bind: ${it.message}")
            0
        }
        if (dataPort > 0) Log.i(TAG_WS, "Real multistream data channels listening on port=$dataPort")

        // Late-bound reference so the stream factory can route inbound ACKs before assignment.
        var transferRef: RealFlashTransferRepository? = null

        val transferImpl = RealFlashTransferRepository(
            streamChannelFactory = { channelId, peerDeviceId ->
                // Real multistream: dedicated TCP data channel to the intended peer.
                // Falls back to the main WebSocket (multiplexed) when the peer's data server
                // is unreachable/old build — dispatcher semantics are identical either way.
                val active = networkImpl.activeSessions.value
                val targeted = peerDeviceId?.let { id -> active[FlashDeviceId(id)] }
                val wsSession = (targeted ?: active.values.firstOrNull()) as? WsSession

                fun wsFallback(): StreamChannel? {
                    if (wsSession == null) {
                        Log.w(TAG_TRANSFER, "StreamChannel[$channelId] no session for peer=$peerDeviceId")
                        return null
                    }
                    return object : StreamChannel {
                        override val id: Int = channelId
                        override suspend fun sendFrame(frameBytes: ByteArray): Boolean =
                            wsSession.connection.sendBinary(frameBytes)
                    }
                }

                if (dataPort <= 0 || peerDeviceId == null) return@RealFlashTransferRepository wsFallback()
                val endpoint = networkImpl.endpointOf(peerDeviceId) ?: return@RealFlashTransferRepository wsFallback()

                // Probe peer's data port: convention is wsPort+1..+20 (server binds its own).
                var probeOffset = dataPortCache[peerDeviceId]
                var channel: com.transfer.flash.core.network.datachannel.DataChannelClient.DataSendChannel? = null
                val offsets = listOfNotNull(probeOffset) + (1..20).filter { it != probeOffset }
                for (offset in offsets) {
                    val candidate = com.transfer.flash.core.network.datachannel.DataChannelClient.connect(
                        host = endpoint.first,
                        port = endpoint.second + offset,
                        targetDeviceId = identity.deviceId.value,
                        channelId = channelId,
                        onFrame = { bytes ->
                            // Inbound on OUR outbound channel = receiver ACKs/COMPLETE.
                            transferRef?.onInboundFrame(bytes)
                        },
                        onClosed = { },
                        localDeviceId = identity.deviceId.value,
                    )
                    if (candidate != null) {
                        dataPortCache[peerDeviceId] = offset
                        channel = candidate
                        Log.i(TAG_TRANSFER, "StreamChannel[$channelId] real socket → ${endpoint.first}:${endpoint.second + offset}")
                        break
                    }
                }

                channel?.let { dc ->
                    object : StreamChannel {
                        override val id: Int = channelId
                        override suspend fun sendFrame(frameBytes: ByteArray): Boolean = dc.send(frameBytes)
                    }
                } ?: run {
                    Log.w(TAG_TRANSFER, "StreamChannel[$channelId] data-channel connect failed; WS fallback")
                    wsFallback()
                }
            },
            fileSourceOpener = { uriString ->
                openSource(uriString, appContext)
            },
            transferDao = db.transferDao(),
            transferChunkDao = db.transferChunkDao(),
        )

        val chatImpl = RealFlashChatRepository(
            localDeviceId = identity.deviceId.value,
            localDisplayName = identity.friendlyName,
            conversationDao = db.conversationDao(),
            messageDao = db.messageDao(),
            outboxDao = db.outboxDao(),
            receiptDao = db.receiptDao(),
            draftDao = db.draftDao(),
            recentSearchDao = db.recentSearchDao(),
            transportSink = { targetDeviceId, wireFrame ->
                val session = networkImpl.activeSessions.value[FlashDeviceId(targetDeviceId)] as? WsSession
                if (session == null) {
                    Log.w(TAG_CHAT, "Failed to dispatch chat wireFrame: no active session for $targetDeviceId")
                    return@RealFlashChatRepository false
                }
                // Field-encoded text framing (colon-safe; message text may contain any characters).
                val frameText = when (wireFrame) {
                    is MessageWireFrame.TextMessage -> FlashTextFraming.encodeFields(
                        MSG_PREFIX,
                        listOf(
                            "localId" to wireFrame.localId,
                            "conversationId" to wireFrame.conversationId,
                            "senderId" to wireFrame.senderId,
                            "senderName" to (wireFrame.senderName ?: "Peer"),
                            "sentAt" to wireFrame.sentAt.toString(),
                            "text" to wireFrame.text,
                        ),
                    )
                    is MessageWireFrame.DeliveryReceipt -> FlashTextFraming.encodeFields(
                        RECEIPT_PREFIX,
                        listOf(
                            "messageId" to wireFrame.messageId,
                            "conversationId" to wireFrame.conversationId,
                            "memberId" to wireFrame.memberId,
                            "deliveredAt" to wireFrame.deliveredAt.toString(),
                        ),
                    )
                    else -> return@RealFlashChatRepository false
                }
                val sent = session.connection.sendText(frameText)
                Log.i(TAG_CHAT, "Dispatched chat frame to $targetDeviceId (success=$sent)")
                sent
            },
        )

        // Observe active WebSocket sessions for incoming chat messages and binary file chunks.
        // Collector jobs are tracked per session and cancelled when the session leaves the map
        // (prevents zombie collectors double-handling frames after reconnect/glare).
        val sessionJobs = ConcurrentHashMap<WsSession, Job>()

        // Receive-pause/cancel gate: while an inbound transfer is paused, binary collection
        // suspends BEFORE pulling the next frame; the bounded channel fills and TCP backpressure
        // throttles legacy peers. Same-build peers also receive the FLASH_XFER wire control
        // frame (below), which pauses their dispatcher at the application level — required for
        // dedicated data channels where WS backpressure doesn't apply.
        //
        // Tracked as a SET of paused transfer ids, not a boolean: with two inbound transfers
        // paused, resuming one used to ungate the socket for both.
        val pausedIntakeIds = MutableStateFlow<Set<String>>(emptySet())
        appScope.launch {
            transferImpl.incomingControl.collect { control ->
                when (control.action) {
                    RealFlashTransferRepository.ACTION_PAUSE -> {
                        pausedIntakeIds.update { it + control.transferId }
                        Log.i(TAG_TRANSFER, "Incoming intake PAUSED transferId=${control.transferId} paused=${pausedIntakeIds.value.size}")
                    }
                    RealFlashTransferRepository.ACTION_RESUME -> {
                        pausedIntakeIds.update { it - control.transferId }
                        Log.i(TAG_TRANSFER, "Incoming intake RESUMED transferId=${control.transferId} paused=${pausedIntakeIds.value.size}")
                    }
                    RealFlashTransferRepository.ACTION_CANCEL -> {
                        // Remote cancel: tear down sink + pipeline session; un-gate intake.
                        openHandles.remove(control.transferId)?.let { handle ->
                            runCatching { handle.close() }
                        }
                        receivePipeline.cancelSession(control.transferId)
                        pausedIntakeIds.update { it - control.transferId }
                        Log.i(TAG_TRANSFER, "Incoming transfer CANCELLED transferId=${control.transferId}")
                    }
                }
            }
        }

        // Wire-level control plane: deliver repo control intents to the counterpart peer as
        // FLASH_XFER text frames over its WebSocket session (ADR-018).
        appScope.launch {
            transferImpl.outgoingControl.collect { control ->
                val peerId = control.peerDeviceId ?: return@collect
                val session = networkImpl.activeSessions.value[FlashDeviceId(peerId)] as? WsSession
                if (session == null) {
                    Log.w(TAG_TRANSFER, "Cannot deliver XFER ${control.action}: no session for $peerId")
                    return@collect
                }
                val frame = FlashTextFraming.encodeFields(
                    XFER_PREFIX,
                    listOf(
                        "action" to control.action,
                        "transferId" to control.transferId,
                    ),
                )
                val ok = session.connection.sendText(frame)
                Log.i(TAG_TRANSFER, "XFER ${control.action} → $peerId (sent=$ok) transferId=${control.transferId}")
            }
        }

        appScope.launch {
            networkImpl.activeSessions.collect { sessions ->
                sessionJobs.keys.filterNot { it in sessions.values }.forEach { stale ->
                    sessionJobs.remove(stale)?.cancel()
                    Log.d(TAG_WS, "Cancelled collectors for stale session peer=${stale.peer.friendlyName}")
                }
                sessions.values.forEach { session ->
                    if (session is WsSession && !sessionJobs.containsKey(session)) {
                        sessionJobs[session] = appScope.launch {
                            launch {
                                session.incomingText.collect { text ->
                                    handleInboundText(chatImpl, transferImpl, text)
                                }
                            }
                            launch {
                                while (true) {
                                    // Block BEFORE pulling the next frame while paused
                                    // (channel fills → WS read loop blocks → TCP backpressure).
                                    pausedIntakeIds.first { it.isEmpty() }
                                    val data = runCatching { session.awaitBinaryFrame() }
                                        .getOrElse { break } // channel closed: session gone
                                    handleInboundBinary(
                                        transferImpl = transferImpl,
                                        receivePipeline = receivePipeline,
                                        openHandles = openHandles,
                                        incomingMeta = incomingMeta,
                                        peerLabel = session.peer.friendlyName,
                                        peerDeviceId = session.peerDeviceId.value,
                                        data = data,
                                        reply = { bytes -> session.connection.sendBinary(bytes) },
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }

        composite = engine
        network = networkImpl
        transferRepo = transferImpl
        chatRepo = chatImpl
        transferRef = transferImpl
        router.transfer = transferImpl
        dataServer = dcServer

        // Auto-start foreground service so screen-off or background doesn't kill the server
        runCatching { FlashBackgroundService.start(appContext) }

        return composite!!
    }

    /**
     * Resolves a send-side source stream. The dummy test URI intentionally streams generated
     * deterministic bytes (Dev Console 10MB benchmark); real content URIs must open cleanly —
     * failures THROW so a broken source can never silently transfer garbage.
     */
    private fun openSource(uriString: String, appContext: Context): InputStream {
        if (uriString == TEST_PAYLOAD_URI) {
            return DeterministicPayloadInputStream(TOTAL_TEST_BYTES)
        }
        require(uriString.startsWith("content://") || uriString.startsWith("file://")) {
            "Unsupported source descriptor: $uriString"
        }
        return appContext.contentResolver.openInputStream(android.net.Uri.parse(uriString))
            ?: throw IOException("Content resolver returned null stream for $uriString")
    }

    private suspend fun handleInboundText(chatImpl: RealFlashChatRepository, transferImpl: RealFlashTransferRepository, text: String) {
        val msgFields = FlashTextFraming.parseFields(text, MSG_PREFIX)
        if (msgFields != null) {
            val localId = msgFields["localId"] ?: return
            chatImpl.onInboundWireFrame(
                MessageWireFrame.TextMessage(
                    localId = localId,
                    conversationId = msgFields["conversationId"] ?: "",
                    senderId = msgFields["senderId"] ?: "",
                    senderName = msgFields["senderName"] ?: "Peer",
                    sentAt = msgFields["sentAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
                    text = msgFields["text"] ?: "",
                ),
            )
            return
        }
        val receiptFields = FlashTextFraming.parseFields(text, RECEIPT_PREFIX)
        if (receiptFields != null) {
            chatImpl.onInboundWireFrame(
                MessageWireFrame.DeliveryReceipt(
                    messageId = receiptFields["messageId"] ?: return,
                    conversationId = receiptFields["conversationId"] ?: "",
                    memberId = receiptFields["memberId"] ?: "",
                    deliveredAt = receiptFields["deliveredAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
                ),
            )
            return
        }
        val xferFields = FlashTextFraming.parseFields(text, XFER_PREFIX)
        if (xferFields != null) {
            val action = xferFields["action"] ?: return
            val transferId = xferFields["transferId"] ?: return
            transferImpl.onRemoteTransferControl(transferId, action)
            return
        }
        Log.w(TAG_CHAT, "Received unrecognized text frame (${text.length} chars)")
    }

    private fun handleInboundBinary(
        transferImpl: RealFlashTransferRepository,
        receivePipeline: ReceivePipeline,
        openHandles: ConcurrentHashMap<String, RandomAccessSinkHandle>,
        incomingMeta: ConcurrentHashMap<String, ChunkFrame.FileStart>,
        peerLabel: String,
        peerDeviceId: String?,
        data: ByteArray,
        reply: (ByteArray) -> Boolean,
    ) {
        Log.d(TAG_TRANSFER, "Received binary frame: ${data.size} bytes from $peerLabel")
        // 1. First route to active senders (ACKs or COMPLETE from receiver)
        if (transferImpl.onInboundFrame(data)) {
            Log.d(TAG_TRANSFER, "Inbound binary frame consumed by sender dispatcher")
            return
        }

        // 2. If not consumed by a sender, route to receiver pipeline
        val events = receivePipeline.onFrame(data)
        for (event in events) {
            when (event) {
                is ReceiveEvent.SessionStarted -> {
                    val frame = event.frame
                    incomingMeta[frame.transferId] = frame
                    transferImpl.onIncomingStarted(
                        transferId = frame.transferId,
                        fileId = frame.fileId,
                        fileName = frame.fileName,
                        totalBytes = frame.totalBytes,
                        peerName = peerLabel,
                        peerDeviceId = peerDeviceId,
                    )
                    Log.i(TAG_TRANSFER, "Receiving '${frame.fileName}' (${frame.totalBytes} bytes, ${frame.totalChunks} chunks) from $peerLabel")
                }
                is ReceiveEvent.AckBatchReady -> {
                    Log.d(TAG_TRANSFER, "Receiver emitting ACK batch with ${event.frame.indexes.size} indexes")
                    updateIncomingProgress(transferImpl, receivePipeline, incomingMeta, event.frame.transferId)
                    reply(ChunkFrame.serialize(event.frame))
                }
                is ReceiveEvent.Completed -> {
                    val handle = openHandles.remove(event.frame.transferId)
                    handle?.flush()
                    handle?.close()
                    transferImpl.onIncomingCompleted(event.frame.transferId, event.frame.verified)
                    Log.i(TAG_TRANSFER, "Receiver completed transferId=${event.frame.transferId} verified=${event.frame.verified}")
                    reply(ChunkFrame.serialize(event.frame))
                }
                is ReceiveEvent.Rejected -> {
                    // Late ACK/COMPLETE arriving after our own dispatcher resolved is benign
                    // noise on a symmetric mesh — debug level; everything else warns.
                    if (event.reason == com.transfer.flash.core.transfer.chunked.RejectReason.UNEXPECTED_DIRECTION) {
                        Log.d(TAG_TRANSFER, "Late/unmatched frame ignored: reason=UNEXPECTED_DIRECTION transferId=${event.transferId}")
                    } else {
                        Log.w(TAG_TRANSFER, "Receiver rejected chunk frame: reason=${event.reason} transferId=${event.transferId} index=${event.index}")
                    }
                }
            }
        }
    }

    /**
     * Transport-agnostic inbound ChunkFrame routing used by BOTH the WebSocket session collector
     * and the dedicated data-channel server (real multistream).
     */
    class DataChannelRouter internal constructor(
        private val receivePipeline: ReceivePipeline,
        private val openHandles: ConcurrentHashMap<String, RandomAccessSinkHandle>,
        private val incomingMeta: ConcurrentHashMap<String, ChunkFrame.FileStart>,
    ) {
        /** Late-bound because the repo is constructed after this router in ensureStarted. */
        @Volatile
        var transfer: RealFlashTransferRepository? = null

        fun onBytes(peerLabel: String, peerDeviceId: String?, bytes: ByteArray, reply: (ByteArray) -> Boolean) {
            val impl = transfer ?: return
            handleInboundBinary(impl, receivePipeline, openHandles, incomingMeta, peerLabel, peerDeviceId, bytes, reply)
        }
    }

    /** Recomputes verified bytes for an inbound transfer from the pipeline's done-set. */
    private fun updateIncomingProgress(
        transferImpl: RealFlashTransferRepository,
        receivePipeline: ReceivePipeline,
        incomingMeta: ConcurrentHashMap<String, ChunkFrame.FileStart>,
        transferId: String,
    ) {
        val start = incomingMeta[transferId] ?: return
        val done = receivePipeline.doneIndexes(transferId) ?: return
        var bytes = 0L
        for (index in done) {
            bytes += minOf(start.chunkSize.toLong(), start.totalBytes - index.toLong() * start.chunkSize)
        }
        transferImpl.onIncomingProgress(transferId, bytes)
    }

    /** Strips anything that could escape the intended directory (path-traversal guard, AGENTS.md §19). */
    private fun sanitizePathComponent(raw: String): String =
        raw.replace(Regex("[^A-Za-z0-9._ ()-]"), "_").trim('.').ifBlank { "unnamed" }.take(120)

    /** Stops advertising/browsing, sessions, and releases the ephemeral port. Idempotent. */
    suspend fun stopAll() = lifecycleMutex.withLock {
        val currentEngine: CompositeDiscovery?
        val currentNetwork: WsFlashNetwork?
        synchronized(this) {
            currentEngine = composite
            currentNetwork = network
            composite = null
            network = null
            transferRepo = null
            chatRepo = null
        }
        binderJob?.cancel()
        binderJob = null
        dataServer?.stop()
        dataServer = null
        currentEngine?.stopAll()
        currentNetwork?.stop()
    }

    const val TOTAL_TEST_BYTES: Long = 10L * 1024 * 1024
}

/**
 * Deterministic pseudo-random byte stream for transfer testing. Same seed => same bytes, so a
 * future end-to-end check can compare digests across devices without shipping a test file.
 */
class DeterministicPayloadInputStream(
    private val totalBytes: Long,
    private val seed: Long = 0x464C615348L,
) : InputStream() {

    private val rng = java.util.Random(seed)
    private val buffer = ByteArray(BUFFER_SIZE).also(rng::nextBytes)
    private var remaining: Long = totalBytes
    private var bufferPos: Int = BUFFER_SIZE

    override fun read(): Int {
        if (remaining <= 0) return -1
        if (bufferPos >= BUFFER_SIZE) {
            bufferPos = 0
        }
        remaining--
        return buffer[bufferPos++].toInt() and 0xFF
    }

    override fun read(b: ByteArray, off: Int, len: Int): Int {
        if (remaining <= 0) return -1
        if (bufferPos >= BUFFER_SIZE) bufferPos = 0
        val count = minOf(len.toLong(), remaining, (BUFFER_SIZE - bufferPos).toLong()).toInt()
        System.arraycopy(buffer, bufferPos, b, off, count)
        bufferPos += count
        remaining -= count
        return count
    }

    companion object {
        private const val BUFFER_SIZE = 64 * 1024
    }
}
