@file:OptIn(com.transfer.flash.core.common.annotation.FlashInternalApi::class)

package com.transfer.flash.debug

import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.net.wifi.WifiManager
import android.os.Build
import android.os.PowerManager
import android.util.Log
import androidx.core.content.ContextCompat
import com.transfer.flash.core.common.model.FlashDeviceId
import com.transfer.flash.core.common.perf.FlashPerformanceMode
import com.transfer.flash.core.common.protocol.FlashTextFraming
import com.transfer.flash.core.discovery.core.CompositeDiscovery
import com.transfer.flash.core.discovery.core.FlashAdvertisedIdentity
import com.transfer.flash.core.discovery.core.FlashDiscoveryMode
import com.transfer.flash.core.messaging.FlashChatRepository
import com.transfer.flash.core.messaging.RealFlashChatRepository
import com.transfer.flash.core.messaging.protocol.GroupFrameCodec
import com.transfer.flash.core.messaging.protocol.GroupWireFrame
import com.transfer.flash.core.messaging.protocol.MessageWireFrame
import com.transfer.flash.core.network.FlashNetwork
import com.transfer.flash.core.network.bridge.DiscoveryRouteBinder
import com.transfer.flash.core.network.ws.WsFlashNetwork
import com.transfer.flash.core.network.ws.WsSession
import com.transfer.flash.core.security.crypto.FlashFingerprint
import com.transfer.flash.core.security.crypto.KeystoreFlashCrypto
import com.transfer.flash.core.security.trust.AndroidPreferencesTrustStore
import com.transfer.flash.core.calling.CallCoordinator
import com.transfer.flash.core.calling.FlashWebRtcEngine
import com.transfer.flash.core.calling.model.FlashCallDirection
import com.transfer.flash.core.calling.model.FlashCallState
import com.transfer.flash.core.calling.protocol.CallFrameCodec
import com.transfer.flash.core.calling.protocol.CallWireFrame
import com.transfer.flash.calling.FlashCallRinger
import com.transfer.flash.calling.FlashCallService
import com.transfer.flash.pairing.PairingCoordinator
import com.transfer.flash.net.AutoConnectGate
import com.transfer.flash.core.transfer.FlashTransferRepository
import com.transfer.flash.core.transfer.RealFlashTransferRepository
import com.transfer.flash.core.engine.store.RoomTransferStore
import com.transfer.flash.core.transfer.chunked.ChunkFrame
import com.transfer.flash.core.transfer.chunked.IncrementalSha256
import com.transfer.flash.core.transfer.chunked.ReceiveEvent
import com.transfer.flash.core.transfer.chunked.ReceivePipeline
import com.transfer.flash.core.transfer.chunked.Sha256
import com.transfer.flash.core.transfer.multistream.StreamChannel
import com.transfer.flash.core.transfer.policy.FileRandomAccessSinkHandle
import com.transfer.flash.core.transfer.policy.RandomAccessChunkSink
import com.transfer.flash.core.transfer.policy.RandomAccessSinkHandle
import com.transfer.flash.core.transfer.policy.TransferReconnectResumePolicy
import com.transfer.flash.core.common.result.FlashResult
import com.transfer.flash.identity.AppIdentity
import com.transfer.flash.notifications.FlashNotificationManager
import java.io.File
import java.io.IOException
import java.io.InputStream
import java.util.Locale
import java.util.UUID
import java.util.concurrent.ConcurrentHashMap
import kotlin.concurrent.Volatile
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.NonCancellable
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.isActive
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import okio.source

/**
 * Process-wide engine holder for the debug Dev Console and background service.
 *
 * Utilizes [WsFlashNetwork] as the full-duplex WebSocket mesh network layer,
 * wired to [RealFlashChatRepository] for instant messaging and [RealFlashTransferRepository]
 * with [ReceivePipeline] for chunked binary file transfers.
 *
 * Received files land at `<external-files>/FlashReceived/<transferId>/<safeFileName>` written
 * via random-access handles at exact chunk offsets (`index * chunkSize`), which is REQUIRED
 * for correct out-of-order multi-stream assembly (ADR-015).
 */
object DiscoveryEngineHolder {

    private const val TAG_DISCOVERY = "DISCOVERY"
    private const val TAG_TRANSFER = "TRANSFER"
    private const val TAG_CHAT = "CHAT"
    private const val TAG_WS = "WS"

    /** Explicit Dev Console test payload URI — intentionally streams generated bytes. */
    private const val TEST_PAYLOAD_URI = "file:///dummy/test_payload.bin"

    /**
     * How long auto-resume waits after a session comes up before re-offering. Long enough for
     * `WsFlashNetwork.registerSession` to have closed the loser of a two-way dial, short next to the
     * seconds the link was already down.
     */
    private const val SETTLE_BEFORE_RESUME_MS = 750L

    private const val MSG_PREFIX = "FLASH_MSG"
    private const val RECEIPT_PREFIX = "FLASH_RCPT"
    private const val READ_PREFIX = "FLASH_READ"
    private const val REACT_PREFIX = "FLASH_REACT"
    private const val TYPING_PREFIX = "FLASH_TYPING"
    private const val XFER_PREFIX = "FLASH_XFER"
    private const val PAIR_PREFIX = "FLASH_PAIR"

    @Volatile
    private var composite: CompositeDiscovery? = null

    @Volatile
    private var network: WsFlashNetwork? = null

    @Volatile
    private var transferRepo: FlashTransferRepository? = null

    @Volatile
    private var chatRepo: FlashChatRepository? = null

    @Volatile
    private var dataServer: com.transfer.flash.core.network.datachannel.DataChannelServer? = null

    @Volatile
    private var pairing: PairingCoordinator? = null

    @Volatile
    private var callCoordinator: CallCoordinator? = null

    /**
     * Owned here rather than by [FlashCallService] or the UI: a call has to ring even when the app
     * is closed (no activity) and even if the platform refuses to promote the call service to the
     * foreground. The engine outlives both, so the ring follows the call state machine for as long
     * as signaling exists. Released only in [stopAll].
     */
    @Volatile
    private var callRinger: FlashCallRinger? = null

    private var binderJob: Job? = null
    private var autoConnectJob: Job? = null
    private var callRingJob: Job? = null

    /**
     * Attempt-bounding gate for the auto-connect sweep, hoisted to a field so the screen-on
     * re-arm ([onScreenOn]) shares the same gate state as the periodic loop instead of racing
     * a second, independent gate.
     */
    @Volatile
    private var autoConnectGate: AutoConnectGate? = null

    /** Local device id, cached so [onScreenOn] can run a sweep without re-reading identity. */
    @Volatile
    private var localDeviceId: String? = null

    /**
     * Attempt budget for restarting roam-killed sends, hoisted to a field so the budget survives
     * individual session-up edges — a per-edge instance would grant an unbounded number of attempts,
     * which is the thing the policy exists to prevent (ERROR-035).
     */
    private val reconnectResume = TransferReconnectResumePolicy()

    /**
     * Application context, cached for the engine's lifetime so the hooks that fire *outside* a
     * caller-supplied context — [onScreenOn]'s foreground-promotion retry and the Wi-Fi rejoin
     * hook handed to [WsFlashNetwork] — can reach [FlashBackgroundService]. Cleared by [stopAll];
     * an application context is a process-lifetime singleton, so holding it leaks nothing.
     */
    @Volatile
    private var appContextRef: Context? = null

    /**
     * Screen-on / user-present re-arm receiver, registered for the ENGINE's lifetime (ERROR-031).
     *
     * It used to live in [FlashBackgroundService], registered in `onCreate` and unregistered in
     * `onDestroy`. That service destroys its own instance when Android 12+ refuses its foreground
     * promotion while deliberately leaving the engine running — so the refused path tore down the
     * engine's only way to notice the screen coming back, leaving it with no foreground service AND
     * no re-arm. Exactly the same reasoning that moved the power locks here.
     *
     * These broadcasts cannot be declared in the manifest, so runtime registration is the only
     * option. Held from [startEngineLocked] until [stopAll].
     */
    @Volatile
    private var screenReceiver: BroadcastReceiver? = null

    // Bug 3: auto-download settings, mirrored from FlashSettingsDataStore by AppEngine
    @Volatile
    var autoDownloadVoice: Boolean = true
    @Volatile
    var autoDownloadImage: Boolean = true
    @Volatile
    var autoDownloadVideo: Boolean = false
    @Volatile
    var autoDownloadFile: Boolean = false

    /**
     * ERROR-031 / D8: "Prioritise voice quality", mirrored from FlashSettingsDataStore by AppEngine
     * and read by [CallCoordinator] once a second for the life of a call.
     *
     * A mirrored `var` rather than a Flow handed to `core:calling`, for the same reason the
     * auto-download flags above are: the calling module must not know that DataStore exists
     * (ADR-024), and the coordinator only ever needs the value at the instant it asks.
     */
    @Volatile
    var prioritiseVoiceQuality: Boolean = true

    /**
     * ERROR-033: the device's performance tier, mirrored from `FlashSettingsDataStore` by
     * `AppEngine` (which resolves an unset/"auto" preference by classifying the hardware).
     *
     * A mirrored `var` read through a lambda for the same ADR-024 reason as
     * [prioritiseVoiceQuality]: `core:calling` and `core:network` must not know DataStore exists.
     *
     * Defaults to [FlashPerformanceMode.HIGH] — i.e. the stack's pre-tiering behaviour — so that
     * anything reading this before the mirror is installed behaves exactly as it did before this
     * feature existed. A `LOW` default would silently degrade every device during boot.
     *
     * Read per use, never captured: pinning a tier from Settings takes effect on the next call
     * and the next connection without a restart.
     */
    @Volatile
    var performanceMode: FlashPerformanceMode = FlashPerformanceMode.HIGH

    /**
     * Voice-call quiet flag: true while a call is ACTIVE, driven by the [CallCoordinator.activeCall]
     * collector next to the ringer wiring. While set, the auto-connect sweep is skipped and
     * discovery drops to ECO (see [setCallActive]): both exist to keep mDNS chatter and TCP dial
     * bursts off the half-duplex radio carrying Opus/RTP on low-end devices. Read per sweep tick,
     * never captured, so a mid-call state change takes effect on the next tick at the latest.
     */
    @Volatile
    private var callActive = false

    /**
     * Bug 3: invoked by [handleInboundBinary] after [RealFlashTransferRepository.onIncomingOffered]
     * so the auto-download policy can auto-accept known MIME types without user interaction.
     * Set inside [ensureStarted] to capture the local [acceptOffer] lambda.
     */
    @Volatile
    var onIncomingOffer: ((String) -> Unit)? = null

    // #16: recreatable so stopAll can cancel every collector/session job launched on it. A cancelled
    // CoroutineScope stays cancelled, so ensureStarted swaps in a fresh one when restarting.
    private var appScope = newAppScope()

    private fun newAppScope() = CoroutineScope(SupervisorJob() + Dispatchers.Default)

    /**
     * CPU wake lock keeping the mesh alive across screen-off / Doze. Without it the CPU is throttled,
     * so the WebSocket keepalive pings stall and inbound frames are processed far too late.
     *
     * ERROR-026: these locks belong to the ENGINE's lifetime, not to a
     * [FlashBackgroundService] instance. The service used to own them, which meant its
     * foreground-refused path (`startForeground` rejected on a sticky restart while backgrounded,
     * then `stopSelf`) released them in `onDestroy` while deliberately leaving the engine running
     * in-process — disarming both power locks in precisely the situation they exist for. Held from
     * [ensureStarted] until [stopAll].
     */
    @Volatile
    private var wakeLock: PowerManager.WakeLock? = null

    /**
     * Keeps the Wi-Fi radio fully powered while backgrounded. In power-save the radio parks between
     * beacons and physically drops packets our sockets and mDNS multicast reception depend on — a
     * loss no software watchdog can forgive, unlike a late keepalive tick.
     * `WIFI_MODE_FULL_LOW_LATENCY` (API 29+) additionally biases the radio toward low latency.
     * See [wakeLock] for why the engine owns this rather than the service.
     */
    @Volatile
    private var wifiLock: WifiManager.WifiLock? = null

    /** Serializes start/stop so racing callers cannot leak duplicate NSD engines/servers. */
    private val lifecycleMutex = Mutex()

    fun current(): CompositeDiscovery? = composite

    fun currentNetwork(): FlashNetwork? = network

    fun currentTransfers(): FlashTransferRepository? = transferRepo

    fun currentChats(): FlashChatRepository? = chatRepo

    fun currentPairing(): PairingCoordinator? = pairing

    fun currentCallCoordinator(): CallCoordinator? = callCoordinator

    /**
     * Boots the whole stack once and returns the live discovery engine; later calls no-op.
     *
     * Runs [NonCancellable] on purpose (ERROR-026). Startup binds the WebSocket server socket,
     * registers the NSD advertisement and opens the encrypted database BEFORE it publishes
     * [composite], and every one of those side effects outlives the caller's coroutine scope. A
     * caller whose scope died mid-startup — [FlashBackgroundService] calling `stopSelf` when Android
     * 12+ refuses its foreground promotion, or an activity being destroyed — used to abort setup
     * partway, leaving a bound socket, a live NSD registration and an open database behind while the
     * holder still reported "not started". The next call then built a SECOND stack beside the
     * orphan. Cancellation cannot help here: only finishing setup keeps the holder's state and the
     * process's real resources in agreement. [stopAll] is the way to tear the engine down.
     */
    suspend fun ensureStarted(context: Context): CompositeDiscovery =
        withContext(NonCancellable) { startEngineLocked(context) }

    private suspend fun startEngineLocked(context: Context): CompositeDiscovery = lifecycleMutex.withLock {
        composite?.let { return it }
        // #16: a prior stopAll cancels appScope; a cancelled scope never runs new coroutines, so
        // start fresh before launching this session's collectors.
        if (!appScope.isActive) appScope = newAppScope()
        val appContext = context.applicationContext
        appContextRef = appContext
        // Power locks first: everything below (socket bind, NSD registration, first sessions) needs
        // an awake CPU and a fully-powered radio, and they now outlive any single service instance.
        acquirePowerLocks(appContext)
        registerScreenReceiver(appContext)
        val identity0 = AppIdentity(appContext)
        val identity = FlashAdvertisedIdentity(
            deviceId = FlashDeviceId(
                value = identity0.deviceId.ifBlank { UUID.randomUUID().toString() },
            ),
            friendlyName = identity0.friendlyName.ifBlank { "Flash Device" },
            deviceModel = android.os.Build.MODEL ?: "unknown",
            protocolVersion = 2,
        )

        Log.i(TAG_DISCOVERY, "Starting Flash discovery with deviceId=${identity.deviceId.value} friendlyName=${identity.friendlyName}")

        val transport = com.transfer.flash.core.discovery.nsd.NsdTransport(
            context = appContext,
            apiLevel = com.transfer.flash.core.discovery.nsd.BuildNsdApiLevel,
            directory = com.transfer.flash.core.discovery.core.StandardEndpointDirectory(),
            sweep = { _ -> emptyList() },
        )
        val engine = CompositeDiscovery(transports = listOf(transport))

        val networkImpl = WsFlashNetwork(
            context = appContext,
            localDeviceId = identity.deviceId.value,
            localFriendlyName = identity.friendlyName,
            // ERROR-031 / D7: a Wi-Fi rejoin is one of the few moments a foreground-service
            // promotion that was refused while backgrounded can succeed, and core:network is
            // already watching for it (its own watcher is `internal`, so :app cannot observe the
            // same edge without a second, duplicate ConnectivityManager callback). No-op unless a
            // promotion actually was refused.
            onUsableNetwork = { FlashBackgroundService.retryPromotionIfRefused(appContext) },
            // ERROR-033: keepalive cadence and the reconnect ceiling come from the device's tier.
            // A lambda, not a value: pinning a tier from Settings must reach the next connection
            // and the next redial without restarting the engine.
            transportProfile = { performanceMode.transport },
        )
        binderJob = DiscoveryRouteBinder.observe(appScope, engine.discoveredEndpoints, networkImpl)

        // Start WebSocket network server
        val netStartResult = networkImpl.start(0)
        val serverPort = (netStartResult as? FlashResult.Success)?.value ?: 0
        check(serverPort > 0) { "Network server failed to start: ${(netStartResult as? FlashResult.Failure)?.error}" }

        Log.i(TAG_WS, "WsFlashNetwork server listening on port=$serverPort")

        engine.setMode(FlashDiscoveryMode.STANDARD)
        val result = engine.startAll(serverPort, identity)
        check(result.isSuccess) {
            "Discovery startAll failed: ${(result as? FlashResult.Failure)?.error}"
        }

        // Full-database encryption via SQLCipher with a keystore-wrapped passphrase; explicit
        // migrations, NO destructive fallback (C1.7 / D2) — a schema bump migrates data instead of
        // wiping it, and the on-disk DB is unreadable without this device's keystore.
        val db = com.transfer.flash.core.persistence.db.FlashDatabaseOpener.openEncrypted(
            appContext,
            com.transfer.flash.persistence.KeystorePassphraseProvider(appContext),
            *com.transfer.flash.core.persistence.db.FlashMigrations.ALL,
        )

        // ---- receive-side infrastructure (must precede the send factory wiring) ----
        val receivedDir = File(appContext.getExternalFilesDir(null), "FlashReceived").apply { mkdirs() }
        val openHandles = ConcurrentHashMap<String, RandomAccessSinkHandle>()
        val incomingMeta = ConcurrentHashMap<String, ChunkFrame.FileStart>()
        // transferId -> absolute path of the received file on disk, so completed inbound transfers
        // (and the chat attachment rows they back) can be opened/shared via FileProvider.
        val receivedPaths = ConcurrentHashMap<String, String>()
        // peerDeviceId -> in-flight inbound transferIds, so a session/data-channel drop can fail and
        // clean up every stranded receive for that peer (#4). Sets are concurrent-safe.
        val incomingByPeer = ConcurrentHashMap<String, MutableSet<String>>()
        // Late-bound so the data-channel server listener (built below, before the cleanup closure
        // exists) can forward connection-closed events to the same inbound-cleanup path (#4).
        var onPeerConnectionClosed: ((String) -> Unit)? = null

        /** Per-peer resolved data-port offset from its advertised WS port (probed once). */
        val dataPortCache = ConcurrentHashMap<String, Int>()

        // Late-bound so the receive pipeline's resume seam (built before the repo) can read the
        // repo's in-memory receiver done-set synchronously (#20).
        var transferForResume: RealFlashTransferRepository? = null

        val receivePipeline = ReceivePipeline(
            sink = { _, _ -> Log.w(TAG_TRANSFER, "Legacy shared sink invoked — expected per-transfer sinkFactory") },
            sinkFactory = { start ->
                val safeName = sanitizePathComponent(start.fileName.ifBlank { "received.bin" })
                val safeId = sanitizePathComponent(start.transferId)
                val dest = File(File(receivedDir, safeId), safeName)
                dest.parentFile?.mkdirs()
                receivedPaths[start.transferId] = dest.absolutePath
                val handle = FileRandomAccessSinkHandle(dest, start.totalBytes)
                openHandles[start.transferId] = handle
                Log.i(TAG_TRANSFER, "Receiver destination opened file=${dest.absolutePath} totalBytes=${start.totalBytes} chunkSize=${start.chunkSize}")
                RandomAccessChunkSink(handle, start.chunkSize)
            },
            emitSessionStarted = true,
            // #5: hold every fresh inbound transfer as an OFFER — no destination file is created
            // and no chunk is written until the user accepts (acceptSession resolves the sink).
            requireAcceptance = true,
            // #20: seed a resumed FILE_START's bit-vector from the persisted receiver done-set.
            resumeIndexesProvider = { start ->
                transferForResume?.receiverDoneIndexes(start.transferId) ?: emptyList()
            },
        )

        // Real N-socket multistream: dedicated plain-TCP data channels next to the WS port.
        val router = DataChannelRouter(receivePipeline, openHandles, incomingMeta, receivedPaths, incomingByPeer)
        val dcServer = com.transfer.flash.core.network.datachannel.DataChannelServer(
            localDeviceId = identity.deviceId.value,
            listener = object : com.transfer.flash.core.network.datachannel.DataChannelServer.Listener {
                override fun onFrame(
                    senderDeviceId: String,
                    channelId: Int,
                    payload: ByteArray,
                    reply: (ByteArray) -> Boolean,
                ) {
                    router.onBytes("dc:$channelId", senderDeviceId, payload, reply)
                }

                override fun onConnectionClosed(peerDeviceId: String?, channelId: Int) {
                    // A dropped data channel strands any inbound transfer mid-flight (#4); route the
                    // peer through the same cleanup the WS-session teardown uses.
                    peerDeviceId?.let { pid -> onPeerConnectionClosed?.invoke(pid) }
                }
            },
        )
        val dataPort = runCatching {
            dcServer.start(preferredPort = serverPort + 1)
        }.getOrElse {
            Log.w(TAG_WS, "DataChannelServer failed to bind: ${it.message}")
            0
        }
        if (dataPort > 0) Log.i(TAG_WS, "Real multistream data channels listening on port=$dataPort")

        // Late-bound reference so the stream factory can route inbound ACKs before assignment.
        var transferRef: RealFlashTransferRepository? = null

        val transferImpl = RealFlashTransferRepository(
            streamChannelFactory = { channelId, peerDeviceId ->
                // Real multistream: dedicated TCP data channel to the intended peer.
                // Falls back to the main WebSocket (multiplexed) when the peer's data server
                // is unreachable/old build — dispatcher semantics are identical either way.
                // F1: a NAMED peer with no session fails the stream; the old
                // `?: active.values.firstOrNull()` leaked group-addressed transfers (whose id
                // is a groupId, never a session key) to an arbitrary connected peer.
                val active = networkImpl.activeSessions.value
                val targeted = peerDeviceId?.let { id -> active[FlashDeviceId(id)] }
                val wsSession = (if (peerDeviceId == null) {
                    targeted ?: active.values.firstOrNull()
                } else {
                    targeted
                }) as? WsSession

                fun wsFallback(): StreamChannel? {
                    if (wsSession == null) {
                        Log.w(TAG_TRANSFER, "StreamChannel[$channelId] no session for peer=$peerDeviceId")
                        return null
                    }
                    return object : StreamChannel {
                        override val id: Int = channelId
                        override suspend fun sendFrame(frameBytes: ByteArray): Boolean =
                            wsSession.connection.sendBinary(frameBytes)
                    }
                }

                if (dataPort <= 0 || peerDeviceId == null) return@RealFlashTransferRepository wsFallback()
                val endpoint = networkImpl.endpointOf(peerDeviceId) ?: return@RealFlashTransferRepository wsFallback()

                // Probe peer's data port: convention is wsPort+1..+20 (server binds its own).
                var probeOffset = dataPortCache[peerDeviceId]
                var channel: com.transfer.flash.core.network.datachannel.DataChannelClient.DataSendChannel? = null
                val offsets = listOfNotNull(probeOffset) + (1..20).filter { it != probeOffset }
                for (offset in offsets) {
                    val candidate = com.transfer.flash.core.network.datachannel.DataChannelClient.connect(
                        host = endpoint.first,
                        port = endpoint.second + offset,
                        targetDeviceId = identity.deviceId.value,
                        channelId = channelId,
                        onFrame = { bytes ->
                            // Inbound on OUR outbound channel = receiver ACKs/COMPLETE.
                            transferRef?.onInboundFrame(bytes)
                        },
                        onClosed = { },
                        localDeviceId = identity.deviceId.value,
                    )
                    if (candidate != null) {
                        dataPortCache[peerDeviceId] = offset
                        channel = candidate
                        Log.i(TAG_TRANSFER, "StreamChannel[$channelId] real socket → ${endpoint.first}:${endpoint.second + offset}")
                        break
                    }
                }

                channel?.let { dc ->
                    object : StreamChannel {
                        override val id: Int = channelId
                        override suspend fun sendFrame(frameBytes: ByteArray): Boolean = dc.send(frameBytes)
                    }
                } ?: run {
                    Log.w(TAG_TRANSFER, "StreamChannel[$channelId] data-channel connect failed; WS fallback")
                    wsFallback()
                }
            },
            fileSourceOpener = { uriString ->
                // Phase 13B-2: FileSourceOpener.open() returns okio.Source; openSource() still
                // yields the ContentResolver's InputStream, bridged here with `.source()`.
                openSource(uriString, appContext).source()
            },
            store = RoomTransferStore(db.transferDao(), db.transferChunkDao()),
            // #5: park every outbound send after FILE_START until the receiver accepts (a RESUME).
            // A compliant sender streams nothing pre-accept, so no chunk is ever lost to the gate.
            requireReceiverAcceptance = true,
        )

        // Trust store is shared by chat (peer-name resolution) and pairing (persisted trust). One
        // instance, created before the chat repo so its name resolver can capture it.
        val trustStore = AndroidPreferencesTrustStore(appContext)

        val chatImpl = RealFlashChatRepository(
            localDeviceId = identity.deviceId.value,
            localDisplayName = identity.friendlyName,
            conversationDao = db.conversationDao(),
            messageDao = db.messageDao(),
            outboxDao = db.outboxDao(),
            receiptDao = db.receiptDao(),
            draftDao = db.draftDao(),
            recentSearchDao = db.recentSearchDao(),
            reactionDao = db.reactionDao(),
            groupMemberDao = db.groupMemberDao(),
            groupDeliveryDao = db.groupDeliveryDao(),
            isTrustedPeer = { peerId -> trustStore.isTrusted(peerId) },
            // Online indicator: a peer is online iff it has a live session. activeSessions is keyed
            // by the peer's FlashDeviceId, and a conversationId IS that peer id, so the repo can key
            // presence directly off this id set.
            onlinePeerIds = networkImpl.activeSessions.map { sessions ->
                sessions.keys.mapTo(HashSet()) { it.value }
            },
            // A conversationId is the peer's device UUID; resolve it to the paired friendly name so
            // the chat list / header show the real name instead of the raw id.
            peerNameResolver = { id -> trustStore.getTrustedPeers()[FlashDeviceId(id)] },
            // B4: join live transfer progress onto chat attachment rows so a chat bubble mirrors the
            // Transfers tab (image thumbnail / file card with progress). Completed transfers drop out
            // of activeTransfers; applyAttachment then falls back to the row's stored path so the
            // attachment stays visible and openable.
            attachmentProgress = transferImpl.activeTransfers.map { transfers ->
                transfers.associate { t ->
                    t.id.value to com.transfer.flash.core.messaging.model.FlashAttachmentProgress(
                        progress = if (t.bytesTotal > 0L) {
                            (t.bytesDone.toFloat() / t.bytesTotal.toFloat()).coerceIn(0f, 1f)
                        } else {
                            0f
                        },
                        status = when (t.state) {
                            com.transfer.flash.core.transfer.model.FlashTransferState.Completed,
                            com.transfer.flash.core.transfer.model.FlashTransferState.Verifying ->
                                com.transfer.flash.core.messaging.model.FlashFileTransferStatus.Downloaded
                            com.transfer.flash.core.transfer.model.FlashTransferState.Failed,
                            com.transfer.flash.core.transfer.model.FlashTransferState.Cancelled ->
                                com.transfer.flash.core.messaging.model.FlashFileTransferStatus.Failed
                            com.transfer.flash.core.transfer.model.FlashTransferState.Offered ->
                                com.transfer.flash.core.messaging.model.FlashFileTransferStatus.AwaitingAcceptance
                            else ->
                                com.transfer.flash.core.messaging.model.FlashFileTransferStatus.Transferring
                        },
                        localPath = t.localPath ?: t.sourceUri,
                        speedMbps = t.speedBytesPerSec / 1_000_000f,
                        etaSeconds = t.etaSeconds.toInt(),
                    )
                }
            },
            // Bug 7: inbound-event callbacks → system notifications. The repo fires these
            // only for rows Room actually inserted, so replayed frames can't double-notify;
            // FlashNotificationManager additionally suppresses the conversation the user
            // is reading right now (foreground + open thread).
            onInboundTextMessageWithGroupTitle = { conversationId, senderName, text, groupTitle ->
                FlashNotificationManager.showMessage(
                    appContext,
                    conversationId,
                    senderName,
                    text,
                    groupTitle,
                )
            },
            onInboundAttachmentWithGroupTitle = { conversationId, senderName, fileName, mimeType, groupTitle ->
                FlashNotificationManager.showAttachment(
                    appContext,
                    conversationId,
                    senderName,
                    fileName,
                    mimeType,
                    groupTitle,
                )
            },
            transportSink = { targetDeviceId, wireFrame ->
                val session = networkImpl.activeSessions.value[FlashDeviceId(targetDeviceId)] as? WsSession
                if (session == null) {
                    Log.w(TAG_CHAT, "Failed to dispatch chat wireFrame: no active session for $targetDeviceId")
                    return@RealFlashChatRepository false
                }
                // Field-encoded text framing (colon-safe; message text may contain any characters).
                val frameText = when (wireFrame) {
                    is MessageWireFrame.TextMessage -> FlashTextFraming.encodeFields(
                        MSG_PREFIX,
                        listOf(
                            "localId" to wireFrame.localId,
                            "conversationId" to wireFrame.conversationId,
                            "senderId" to wireFrame.senderId,
                            "senderName" to (wireFrame.senderName ?: "Peer"),
                            "sentAt" to wireFrame.sentAt.toString(),
                            "text" to wireFrame.text,
                            // Reply/quote metadata (#8); empty string when this is not a reply.
                            "replyToId" to (wireFrame.replyToId ?: ""),
                            "replyToPreview" to (wireFrame.replyToPreview ?: ""),
                        ),
                    )
                    is MessageWireFrame.DeliveryReceipt -> FlashTextFraming.encodeFields(
                        RECEIPT_PREFIX,
                        listOf(
                            "messageId" to wireFrame.messageId,
                            "conversationId" to wireFrame.conversationId,
                            "memberId" to wireFrame.memberId,
                            "deliveredAt" to wireFrame.deliveredAt.toString(),
                        ),
                    )
                    is MessageWireFrame.ReadReceipt -> FlashTextFraming.encodeFields(
                        READ_PREFIX,
                        listOf(
                            "conversationId" to wireFrame.conversationId,
                            "memberId" to wireFrame.memberId,
                            "upToMessageId" to wireFrame.upToMessageId,
                            "readAt" to wireFrame.readAt.toString(),
                        ),
                    )
                    is MessageWireFrame.ReactionFrame -> FlashTextFraming.encodeFields(
                        REACT_PREFIX,
                        listOf(
                            "messageId" to wireFrame.messageId,
                            "conversationId" to wireFrame.conversationId,
                            "memberId" to wireFrame.memberId,
                            "emoji" to wireFrame.emoji,
                            "isAdded" to wireFrame.isAdded.toString(),
                        ),
                    )
                    is MessageWireFrame.TypingFrame -> FlashTextFraming.encodeFields(
                        TYPING_PREFIX,
                        listOf(
                            "conversationId" to wireFrame.conversationId,
                            "memberId" to wireFrame.memberId,
                            "memberName" to wireFrame.memberName,
                            "isTyping" to wireFrame.isTyping.toString(),
                            "timestampMs" to wireFrame.timestampMs.toString(),
                        ),
                    )
                }
                val sent = session.connection.sendText(frameText)
                Log.i(TAG_CHAT, "Dispatched chat frame to $targetDeviceId (success=$sent)")
                sent
            },
            groupTransportSink = { targetDeviceId, wireFrame ->
                val session = networkImpl.activeSessions.value[FlashDeviceId(targetDeviceId)] as? WsSession
                    ?: return@RealFlashChatRepository false
                session.connection.sendText(GroupFrameCodec.encode(wireFrame))
            },
        )

        // ---- pairing (C2/C4): persistent identity fingerprint + trust store, glued to the
        // pure DefaultFlashPairingProtocol by PairingCoordinator. Frames ride the same WS text
        // framing as chat/receipts/transfer control, under the FLASH_PAIR prefix. Trust persists
        // to SharedPreferences (AndroidPreferencesTrustStore), so paired peers survive restarts.
        val crypto = KeystoreFlashCrypto(appContext)
        val localFingerprintHex =
            FlashFingerprint.formatHexGroups(FlashFingerprint.fingerprint(crypto.identityPublicKeyEncoded))
        // (trustStore constructed above, shared with the chat repo.)
        // One ephemeral ECDH key reused for the lifetime of this engine (no session encryption is
        // wired yet — the key rides the handshake but is opaque to the current transport).
        val ephemeralPublicKey = crypto.generateEphemeralEcdhKeyPair().publicKeyEncoded
        val pairingCoordinator = PairingCoordinator(
            localFingerprintHex = localFingerprintHex,
            localDeviceId = identity.deviceId.value,
            localName = identity.friendlyName,
            localModel = identity.deviceModel,
            ephemeralPublicKey = ephemeralPublicKey,
            trustStore = trustStore,
            scope = appScope,
            sendToPeer = { peerId, text ->
                // MUST be non-blocking: beginPair is invoked from the UI (main) dispatcher, and a
                // blocking socket write there throws NetworkOnMainThreadException — which WsConnection
                // catches as a write failure and CLOSES the session, tearing down the link the
                // handshake needs. sendTextAsync queues the write on the connection's own IO scope.
                // The boolean reports reachability (is there a live session?), which is exactly the
                // signal beginPair uses for its "Couldn't reach…" feedback.
                val session = networkImpl.activeSessions.value[FlashDeviceId(peerId)] as? WsSession
                if (session != null) {
                    session.connection.sendTextAsync(text)
                    Log.i(TAG_WS, "Pairing sendToPeer id=$peerId queued (hasSession=true)")
                    true
                } else {
                    Log.i(TAG_WS, "Pairing sendToPeer id=$peerId no session")
                    false
                }
            },
        )

        // ---- calling (C7 / ADR-025 / UI-050): WebRTC voice/video, signaling over the same WS
        // mesh text frames under the FLASH_CALL prefix. sendFrame is non-blocking (sendTextAsync),
        // exactly like the pairing path: call control runs on the UI dispatcher when the user taps
        // call/accept/decline and must never block on a socket write from the main thread.
        //
        // The destination peer is EXPLICIT (second lambda arg): call frames carry only callId +
        // our own `from` on the wire, so routing by frame.from would send every frame to ourselves.
        // The coordinator resolves the peer (live session peer, or a busy-decline's new inviter).
        //
        // Installs the audio device module first. WebRtc.configure() throws once a
        // PeerConnectionFactory exists, so this is the last safe moment: after it, the ADM
        // is permanent for the process. Best-effort — a device that refuses still gets a call
        // on libwebrtc's defaults.
        //
        // LOW-tier devices skip the low-latency ADM: the small playout buffer underruns on a
        // weak HAL and each underrun NetEQ-stretches into a latency spike, which jitters more
        // than the default ADM's stable buffering costs. Read once here because the ADM is
        // process-wide — a later tier change takes effect on the next process start.
        FlashWebRtcEngine.configureOnce(
            appContext,
            lowLatencyPlayout = performanceMode != FlashPerformanceMode.LOW,
        )
        val callCoordinator = CallCoordinator(
            localDeviceId = identity.deviceId.value,
            localName = identity.friendlyName,
            scope = appScope,
            // Group Phase 0 trust closure: only paired peers can place or receive calls.
            isTrustedPeer = { peerId -> trustStore.isTrusted(peerId) },
            // Read per sample, not captured once: flipping the switch mid-call has to take effect
            // on that call, not the next one.
            prioritiseVoice = { prioritiseVoiceQuality },
            // ERROR-033: capture size, Opus packetization and the call-recovery windows all come
            // from the device's tier. Read per call for the same reason as above.
            performanceMode = { performanceMode },
            sendFrame = { frame, peerId ->
                val encoded = CallFrameCodec.encode(frame)
                val session = networkImpl.activeSessions.value[FlashDeviceId(peerId)] as? WsSession
                if (session != null) {
                    session.connection.sendTextAsync(encoded)
                    Log.i(TAG_WS, "Call sendFrame action=${frame.javaClass.simpleName} peer=$peerId (hasSession=true)")
                    true
                } else {
                    Log.i(TAG_WS, "Call sendFrame action=${frame.javaClass.simpleName} peer=$peerId no session")
                    false
                }
            },
            // Every terminated call becomes a row in the peer's thread (UI-050). No wire frame is
            // involved: both devices already hold direction, duration and end reason locally, so
            // each writes its own row — which is also why a declined or missed call still appears.
            // Fires on whichever thread ended the call (possibly a WebRTC callback thread), and
            // recordCallEvent only launches on the repository's IO scope, so it never blocks.
            onCallLog = { entry ->
                Log.i(
                    TAG_WS,
                    "Call log peer=${entry.peerId} video=${entry.video} " +
                        "reason=${entry.endReason} durationMs=${entry.durationMs}",
                )
                chatImpl.recordCallEvent(
                    peerDeviceId = entry.peerId,
                    callId = entry.callId,
                    peerName = entry.peerName,
                    outgoing = entry.direction == FlashCallDirection.OUTGOING,
                    video = entry.video,
                    durationMs = entry.durationMs,
                    endedAt = entry.endedAt,
                )
            },
        )

        // Observe active WebSocket sessions for incoming chat messages and binary file chunks.
        // Collector jobs are tracked per session and cancelled when the session leaves the map
        // (prevents zombie collectors double-handling frames after reconnect/glare).
        val sessionJobs = ConcurrentHashMap<WsSession, Job>()

        // Receive-pause/cancel gate: while an inbound transfer is paused, binary collection
        // suspends BEFORE pulling the next frame; the bounded channel fills and TCP backpressure
        // throttles legacy peers. Same-build peers also receive the FLASH_XFER wire control
        // frame (below), which pauses their dispatcher at the application level — required for
        // dedicated data channels where WS backpressure doesn't apply.
        //
        // Tracked as a SET of paused transfer ids, not a boolean: with two inbound transfers
        // paused, resuming one used to ungate the socket for both.
        val pausedIntakeIds = MutableStateFlow<Set<String>>(emptySet())

        // Single idempotent teardown for one inbound transfer: close+drop the sink handle, forget
        // its metadata, drop the pipeline session, un-gate intake, unregister it from its peer, and
        // mark the transfer row failed (#4). Safe to call for an unknown/already-cleaned id.
        val cleanupInbound: (String, String) -> Unit = { transferId, reason ->
            openHandles.remove(transferId)?.let { handle -> runCatching { handle.close() } }
            incomingMeta.remove(transferId)
            receivedPaths.remove(transferId)
            receivePipeline.cancelSession(transferId)
            pausedIntakeIds.update { it - transferId }
            incomingByPeer.values.forEach { it.remove(transferId) }
            transferImpl.onIncomingFailed(transferId, reason)
        }

        // Fail every stranded inbound transfer for a peer whose transport just dropped (#4).
        val failInboundForPeer: (String, String) -> Unit = { peerId, reason ->
            incomingByPeer.remove(peerId)?.toList()?.forEach { transferId ->
                Log.i(TAG_TRANSFER, "Peer $peerId dropped — failing inbound transferId=$transferId ($reason)")
                cleanupInbound(transferId, reason)
            }
        }
        onPeerConnectionClosed = { peerId -> failInboundForPeer(peerId, "data channel closed") }

        // Sends one FLASH_XFER control frame to a peer's WebSocket session (ADR-018). Shared by the
        // outgoingControl collector and the offer-accept path (which must RESUME the sender only
        // AFTER the local sink is resolved, so it cannot go through the fire-and-forget flow).
        val sendXfer: (String, String, String) -> Unit = { peerId, action, transferId ->
            val session = networkImpl.activeSessions.value[FlashDeviceId(peerId)] as? WsSession
            if (session == null) {
                Log.w(TAG_TRANSFER, "Cannot deliver XFER $action: no session for $peerId")
            } else {
                val frame = FlashTextFraming.encodeFields(
                    XFER_PREFIX,
                    listOf("action" to action, "transferId" to transferId),
                )
                val ok = session.connection.sendText(frame)
                Log.i(TAG_TRANSFER, "XFER $action → $peerId (sent=$ok) transferId=$transferId")
            }
        }

        // Accepts a pending inbound OFFER (#5): resolve the deferred sink FIRST (so no early chunk
        // is dropped), surface it as Transferring + a chat bubble, then RESUME the parked sender.
        val acceptOffer: (String) -> Unit = { transferId ->
            val meta = incomingMeta[transferId]
            val pid = transferImpl.activeTransfers.value.find { it.id.value == transferId }?.peerDeviceId
            if (meta == null) {
                Log.w(TAG_TRANSFER, "Accept for unknown offer transferId=$transferId")
            } else if (receivePipeline.acceptSession(transferId)) {
                transferImpl.onIncomingStarted(
                    transferId = transferId,
                    fileId = meta.fileId,
                    fileName = meta.fileName,
                    totalBytes = meta.totalBytes,
                    peerName = pid ?: "",
                    peerDeviceId = pid,
                    localPath = receivedPaths[transferId],
                )
                // #1: mint the inbound attachment bubble now that the user has accepted.
                pid?.let {
                    chatImpl.onInboundAttachment(
                        peerDeviceId = it,
                        transferId = transferId,
                        fileName = meta.fileName,
                        mimeType = guessMimeType(meta.fileName),
                        sizeBytes = meta.totalBytes,
                    )
                }
                // Release the parked sender AFTER the sink exists.
                pid?.let { sendXfer(it, RealFlashTransferRepository.ACTION_RESUME, transferId) }
                Log.i(TAG_TRANSFER, "Accepted offer transferId=$transferId → streaming")
            } else {
                Log.w(TAG_TRANSFER, "acceptSession no-op transferId=$transferId (already open?)")
            }
        }

        // Bug 3: auto-download policy. AppEngine mirrors the per-MIME toggles into
        // autoDownloadVoice/Image/Video/File; when an offer arrives whose MIME category is enabled,
        // accept it immediately (same path as a manual Accept). Otherwise the offer stays pending
        // for the user to accept/decline in the chat bubble.
        onIncomingOffer = { transferId ->
            val meta = incomingMeta[transferId]
            if (meta != null) {
                val mime = guessMimeType(meta.fileName)
                val auto = when {
                    mime.startsWith("audio/") -> autoDownloadVoice
                    mime.startsWith("image/") -> autoDownloadImage
                    mime.startsWith("video/") -> autoDownloadVideo
                    else -> autoDownloadFile
                }
                if (auto) {
                    Log.i(TAG_TRANSFER, "Auto-accepting '${meta.fileName}' (mime=$mime) transferId=$transferId")
                    acceptOffer(transferId)
                }
            }
        }

        // Declines a pending inbound OFFER (#5): drop the never-materialized session and local
        // bookkeeping. The repo already marked the row Cancelled and emitted a CANCEL to the sender.
        val declineOffer: (String) -> Unit = { transferId ->
            receivePipeline.declineSession(transferId)
            incomingMeta.remove(transferId)
            receivedPaths.remove(transferId)
            pausedIntakeIds.update { it - transferId }
            incomingByPeer.values.forEach { it.remove(transferId) }
            Log.i(TAG_TRANSFER, "Declined offer transferId=$transferId")
        }

        appScope.launch {
            transferImpl.incomingControl.collect { control ->
                when (control.action) {
                    RealFlashTransferRepository.ACTION_PAUSE -> {
                        pausedIntakeIds.update { it + control.transferId }
                        Log.i(TAG_TRANSFER, "Incoming intake PAUSED transferId=${control.transferId} paused=${pausedIntakeIds.value.size}")
                    }
                    RealFlashTransferRepository.ACTION_RESUME -> {
                        pausedIntakeIds.update { it - control.transferId }
                        Log.i(TAG_TRANSFER, "Incoming intake RESUMED transferId=${control.transferId} paused=${pausedIntakeIds.value.size}")
                    }
                    RealFlashTransferRepository.ACTION_CANCEL -> {
                        // Remote cancel: tear down sink + pipeline session, un-gate intake, and mark
                        // the row failed via the shared inbound-cleanup path.
                        cleanupInbound(control.transferId, "cancelled by peer")
                        Log.i(TAG_TRANSFER, "Incoming transfer CANCELLED transferId=${control.transferId}")
                    }
                    RealFlashTransferRepository.ACTION_ACCEPT -> acceptOffer(control.transferId)
                    RealFlashTransferRepository.ACTION_DECLINE -> declineOffer(control.transferId)
                }
            }
        }

        // Wire-level control plane: deliver repo control intents to the counterpart peer as
        // FLASH_XFER text frames over its WebSocket session (ADR-018).
        appScope.launch {
            transferImpl.outgoingControl.collect { control ->
                val peerId = control.peerDeviceId ?: return@collect
                val session = networkImpl.activeSessions.value[FlashDeviceId(peerId)] as? WsSession
                if (session == null) {
                    Log.w(TAG_TRANSFER, "Cannot deliver XFER ${control.action}: no session for $peerId")
                    return@collect
                }
                val frame = FlashTextFraming.encodeFields(
                    XFER_PREFIX,
                    listOf(
                        "action" to control.action,
                        "transferId" to control.transferId,
                    ),
                )
                val ok = session.connection.sendText(frame)
                Log.i(TAG_TRANSFER, "XFER ${control.action} → $peerId (sent=$ok) transferId=${control.transferId}")
            }
        }

        appScope.launch {
            networkImpl.activeSessions.collect { sessions ->
                sessionJobs.keys.filterNot { it in sessions.values }.forEach { stale ->
                    sessionJobs.remove(stale)?.cancel()
                    // The WS session is the authoritative "peer gone" signal: fail every inbound
                    // transfer still in flight for it so no handle/row is stranded (#4).
                    failInboundForPeer(stale.peerDeviceId.value, "peer disconnected")
                    // A live call cannot carry ICE without its signaling session, but a mesh roam
                    // takes that session down as a matter of course and the dialer redials it in
                    // seconds. Open a recovery window rather than ending the call (ERROR-033).
                    callCoordinator.onSignalingLost(stale.peerDeviceId.value)
                    Log.d(TAG_WS, "Cancelled collectors for stale session peer=${stale.peer.friendlyName}")
                }
                sessions.values.forEach { session ->
                    if (session is WsSession && !sessionJobs.containsKey(session)) {
                        // Announce our identity fingerprint so the peer can derive the shared
                        // pairing code the moment it taps Pair (see PairingFraming.Hello).
                        Log.i(TAG_WS, "Session up peer=${session.peer.friendlyName} id=${session.peerDeviceId.value} — sending pairing hello")
                        pairingCoordinator.onSessionUp(session.peerDeviceId.value)
                        // Bug 5: a peer session is up (connect/reconnect) — flush the durable
                        // outbox now so messages queued while this peer was offline send. The peer
                        // id additionally makes that member's group deliveries retryable.
                        chatImpl.notifyPeerSessionUp(session.peerDeviceId.value)
                        // F3: ask the returning peer to push any group messages it holds that we
                        // lack (holder-coordinated catch-up, FLASH_GSYNC).
                        chatImpl.sendGroupSyncRequests(session.peerDeviceId.value)
                        // Closes any recovery window the matching onSignalingLost opened, so a roam
                        // that resolved in two seconds does not cost the full grace period, and the
                        // ICE restart offer has a channel to travel on (ERROR-033).
                        callCoordinator.onSignalingRestored(session.peerDeviceId.value)
                        // Restart sends this peer's last disconnect killed. Byte-accurate resume
                        // already existed and nothing called it, so a roam mid-transfer meant a
                        // Failed row until a human tapped retry (ERROR-035).
                        appScope.launch {
                            resumeRoamKilledSends(transferImpl, networkImpl, session.peerDeviceId.value)
                        }
                        sessionJobs[session] = appScope.launch {
                            launch {
                                session.incomingText.collect { text ->
                                    handleInboundText(chatImpl, transferImpl, pairingCoordinator, callCoordinator, session.peerDeviceId.value, text)
                                }
                            }
                            launch {
                                while (true) {
                                    // Block BEFORE pulling the next frame while paused
                                    // (channel fills → WS read loop blocks → TCP backpressure).
                                    pausedIntakeIds.first { it.isEmpty() }
                                    val data = runCatching { session.awaitBinaryFrame() }
                                        .getOrElse { break } // channel closed: session gone
                                    handleInboundBinary(
                                        transferImpl = transferImpl,
                                        receivePipeline = receivePipeline,
                                        openHandles = openHandles,
                                        incomingMeta = incomingMeta,
                                        receivedPaths = receivedPaths,
                                        incomingByPeer = incomingByPeer,
                                        peerLabel = session.peer.friendlyName,
                                        peerDeviceId = session.peerDeviceId.value,
                                        data = data,
                                        reply = { bytes -> session.connection.sendBinary(bytes) },
                                        onAttachmentStarted = { pid, transferId, fileName, totalBytes ->
                                            chatImpl.onInboundAttachment(
                                                peerDeviceId = pid,
                                                transferId = transferId,
                                                fileName = fileName,
                                                mimeType = guessMimeType(fileName),
                                                sizeBytes = totalBytes,
                                            )
                                        },
                                    )
                                }
                            }
                        }
                    }
                }
            }
        }

        composite = engine
        network = networkImpl
        transferRepo = transferImpl
        chatRepo = chatImpl
        pairing = pairingCoordinator
        this.callCoordinator = callCoordinator
        transferRef = transferImpl
        router.transfer = transferImpl
        transferForResume = transferImpl
        // Warm the receiver done-set so a resumed inbound FILE_START seeds its bit-vector (#20).
        appScope.launch { runCatching { transferImpl.preloadReceiverProgress() } }
        dataServer = dcServer

        // Proactively hold a full-duplex session with every discovered peer, dialing from both ends so
        // whichever side's discovery resolves first gets the session up; all traffic then rides that
        // one session and the loser's dial costs nothing. Glare is resolved by
        // WsFlashNetwork.registerSession; AutoConnectGate bounds attempts so an unreachable peer is
        // retried, not hammered.
        //
        // This used to be justified by "the SoftAP/gateway device cannot open a TCP connection to a
        // client station". That is not an Android or Linux rule — the host is the gateway and has a
        // directly connected route. Host-to-client dials failed because WsTransferClient bound them to
        // the first Wi-Fi network CM listed, which a tethered client is never on-link for
        // (ERROR-035, fixed in Ipv4Routing). Dialing both ways is still correct; the reason changed.
        autoConnectJob = appScope.launch {
            val gate = AutoConnectGate()
            autoConnectGate = gate
            localDeviceId = identity.deviceId.value
            while (isActive) {
                // Voice-call quiet: while a call is ACTIVE the radio belongs to Opus/RTP, so no
                // dial bursts. The tick itself keeps running so the sweep resumes on its normal
                // cadence the moment the call ends.
                if (!callActive) {
                    runAutoConnectSweep(engine, networkImpl, identity.deviceId.value, gate)
                }
                delay(AUTO_CONNECT_SWEEP_MS)
            }
        }

        // C7 ringing: the engine — not the UI, not FlashCallService — drives the ringer and the
        // call notification, because an invite that arrives with the app closed still has to ring.
        // Ownership here also means the ring survives a refused foreground-service promotion: the
        // ringtone is a plain MediaPlayer on the ring stream and needs no FGS at all.
        //
        // `collect`, not `collectLatest`: onCallState is a cheap synchronized state machine and
        // dropping an intermediate emission could drop the very edge that stops the ring.
        // FlashCallService.start is called on the ringing edges only; the service stops itself when
        // activeCall goes null, and it de-duplicates repeated starts internally.
        callRinger = FlashCallRinger(appContext)
        callRingJob = appScope.launch {
            callCoordinator.activeCall.collect { state ->
                callRinger?.onCallState(state)
                if (state?.state == FlashCallState.DIALING || state?.state == FlashCallState.RINGING) {
                    FlashCallService.start(appContext)
                }
                setCallActive(state?.state == FlashCallState.ACTIVE, engine)
            }
        }

        // MainActivity.onStart owns foreground-service launch while the app is user-visible.
        // Starting it here after asynchronous engine setup can violate Android 12+ background-start rules.
        return composite!!
    }

    /**
     * One pass of the proactive auto-connect sweep: dials every discovered peer that lacks a
     * live session, bounded by [AutoConnectGate]. Extracted from the periodic loop so the
     * screen-on re-arm ([onScreenOn]) can force an immediate sweep instead of waiting up to
     * [AUTO_CONNECT_SWEEP_MS] for the next tick. Each dial is launched on [appScope] and ends
     * its own gate entry, exactly as the original inline loop did.
     */
    private fun runAutoConnectSweep(
        engine: CompositeDiscovery,
        networkImpl: WsFlashNetwork,
        localId: String,
        gate: AutoConnectGate,
    ) {
        val endpoints = engine.discoveredEndpoints.value
        for (ep in endpoints) {
            val id = ep.deviceId.value
            if (id == localId) continue
            // ERROR-031: ask whether the peer's session is actually carrying traffic, not whether the
            // registry happens to hold one. A session whose socket died without its watchdog noticing
            // used to suppress this sweep indefinitely — the dot stayed Online, every send "succeeded"
            // into the dead socket, and only a force-stop cleared it.
            val hasSession = networkImpl.hasLiveSession(id)
            // ERROR-023 dedup: if the #18 reconnect engine is already backoff-dialing this peer
            // right now, don't fire a redundant dial from the sweep at the same moment — two
            // simultaneous outbound dials to the same peer only widen the glare window.
            if (networkImpl.isReconnectInFlight(id)) continue
            if (!gate.tryBegin(id, hasSession, System.currentTimeMillis())) continue
            appScope.launch {
                Log.i(TAG_WS, "Auto-connect dialing peer=${ep.friendlyName} id=$id at ${ep.hostAddress}:${ep.port}")
                val result = runCatching { networkImpl.connectManual(ep.hostAddress, ep.port) }.getOrNull()
                val ok = result is FlashResult.Success
                Log.i(TAG_WS, "Auto-connect result peer=$id success=$ok")
                gate.end(id)
            }
        }
    }

    /**
     * Voice-call quiet transitions, driven by the [CallCoordinator.activeCall] collector. On the
     * ACTIVE edge: discovery drops to ECO (advertising continues so the device stays visible;
     * browse duty-cycles to 20 s bursts with 100 s idle gaps and the auto-connect sweep stops
     * via [callActive]), and live transfer dispatchers slow their progress watcher via
     * [RealFlashTransferRepository.voiceCallActive]. On the leaving-ACTIVE edge both are
     * restored — the ECO→STANDARD switch wakes an in-flight idle gap immediately, so
     * discovery resumes at full rate without waiting it out.
     *
     * `runCatching` guards the mode switch, never the flag: this runs inside the `collect` loop
     * that also drives the ringer, and a throwing transport must not kill that loop. The flag is
     * set first so the sweep gate holds even if the mode switch fails.
     */
    private suspend fun setCallActive(active: Boolean, engine: CompositeDiscovery) {
        if (active == callActive) return
        callActive = active
        (transferRepo as? RealFlashTransferRepository)?.voiceCallActive = active
        runCatching {
            engine.setMode(if (active) FlashDiscoveryMode.ECO else FlashDiscoveryMode.STANDARD)
        }.onFailure { t ->
            Log.w(TAG_WS, "Call-quiet setMode(${if (active) "ECO" else "STANDARD"}) failed: ${t.message}")
        }
    }

    /**
     * Screen-on / user-present re-arm, driven by the engine-scoped [screenReceiver].
     *
     * Screen-off + Doze can silently drop WebSocket sessions and stall mDNS reception even with
     * the engine's wake/Wi-Fi locks held. When the screen returns we (1) restart discovery
     * browsing so returning peers are re-found, and (2) force an immediate auto-connect sweep so
     * discovered/known peers are re-dialed at once rather than after the next periodic tick.
     *
     * It also retries a foreground-service promotion that was previously refused (ERROR-031 / D7).
     * That retry is best-effort by nature: a runtime-registered `ACTION_SCREEN_ON` is **not** one of
     * Android 12+'s foreground-service-start exemptions, so the attempt only succeeds when the app
     * holds another one — in practice the battery-optimisation exemption, which is why Settings now
     * surfaces it. `startAsForeground()` already swallows a refusal, so a failed retry costs nothing
     * and the flag stays armed for the next opportunity.
     *
     * Safe to call when the engine has not started (no-op).
     */
    fun onScreenOn() {
        appContextRef?.let { FlashBackgroundService.retryPromotionIfRefused(it) }
        reArm("Screen-on")
    }

    /**
     * Manual re-arm behind the conversation's connection-banner Retry button.
     *
     * Same work as [onScreenOn]: the reasons a peer looks offline are identical whether the screen
     * just came back or the user got tired of waiting — a stalled browse, or a dropped session that
     * the backoff engine has not re-dialed yet. `FlashNetwork.retryConnection()` is not the entry
     * point here: the WS mesh implementation inherits its `false` default (only the legacy LAN stack
     * overrides it), so it would report "nothing to retry" for every peer.
     *
     * @return false when the engine has not booted yet, so the caller can tell the user that
     *   tapping again is pointless rather than silently doing nothing.
     */
    fun reconnectNow(): Boolean = reArm("Manual retry")

    /**
     * Shared body of [onScreenOn] / [reconnectNow]; [reason] only tags the log line.
     *
     * Uses restartDiscovery(), not startDiscovery(): the latter delegates to the transport's
     * idempotent startBrowsing(), which returns immediately while the transport still *believes*
     * it is browsing — precisely the state a Doze-stalled radio is in. That made this re-arm a
     * silent no-op exactly when it was needed. restartDiscovery() tears the browse down and
     * re-arms it, so the platform re-delivers every service still present.
     */
    private fun reArm(reason: String): Boolean {
        val engine = composite ?: return false
        val networkImpl = network ?: return false
        val gate = autoConnectGate ?: return false
        val localId = localDeviceId ?: return false
        appScope.launch {
            Log.i(TAG_DISCOVERY, "$reason: restarting discovery browsing and forcing auto-connect sweep")
            runCatching { engine.restartDiscovery() }
                .onFailure { Log.w(TAG_DISCOVERY, "$reason discovery restart failed", it) }
            runAutoConnectSweep(engine, networkImpl, localId, gate)
        }
        return true
    }

    /**
     * Restarts outbound transfers that this peer's previous disconnect failed (ERROR-035).
     *
     * Called on the session-up edge, which is the only moment a resume can succeed: `relaunchSend`
     * needs a live session to carry the re-offer, and the re-offer reproduces the original
     * `wireFileId`/`sourceUri` so the receiver treats it as a continuation and keeps the chunks it has
     * already verified. Nothing else in the app ever triggers that automatically.
     *
     * [SETTLE_BEFORE_RESUME_MS] exists because both ends dial and `WsFlashNetwork.registerSession`
     * closes the loser; a re-offer issued into the losing session fails and spends an attempt from a
     * budget meant for real network failures. Waiting past glare resolution and re-checking the
     * session costs a fraction of a second on a path that has already been down for seconds.
     */
    private suspend fun resumeRoamKilledSends(
        transfers: RealFlashTransferRepository,
        networkImpl: WsFlashNetwork,
        peerDeviceId: String,
    ) {
        delay(SETTLE_BEFORE_RESUME_MS)
        if (networkImpl.activeSessions.value[FlashDeviceId(peerDeviceId)] == null) {
            Log.d(TAG_TRANSFER, "Skipping auto-resume for $peerDeviceId: session did not survive glare")
            return
        }
        val snapshot = transfers.activeTransfers.value
        reconnectResume.retainOnly(snapshot.mapTo(HashSet(snapshot.size)) { it.id })
        val toResume = reconnectResume.onPeerSessionUp(peerDeviceId, snapshot)
        if (toResume.isEmpty()) return
        Log.i(TAG_TRANSFER, "Session up for $peerDeviceId: auto-resuming ${toResume.size} failed send(s)")
        toResume.forEach { transferId ->
            val result = runCatching { transfers.resumeTransfer(transferId) }
            val attempt = reconnectResume.attemptsFor(transferId)
            result
                .onSuccess { outcome ->
                    Log.i(
                        TAG_TRANSFER,
                        "Auto-resume attempt $attempt transferId=${transferId.value} " +
                            "ok=${outcome is FlashResult.Success}",
                    )
                }
                .onFailure { error ->
                    Log.w(TAG_TRANSFER, "Auto-resume attempt $attempt threw transferId=${transferId.value}", error)
                }
        }
    }

    /**
     * Resolves a send-side source stream. The dummy test URI intentionally streams generated
     * deterministic bytes (Dev Console 10MB benchmark); real content URIs must open cleanly —
     * failures THROW so a broken source can never silently transfer garbage.
     */
    private fun openSource(uriString: String, appContext: Context): InputStream {
        if (uriString == TEST_PAYLOAD_URI) {
            return DeterministicPayloadInputStream(TOTAL_TEST_BYTES)
        }
        require(uriString.startsWith("content://") || uriString.startsWith("file://")) {
            "Unsupported source descriptor: $uriString"
        }
        return appContext.contentResolver.openInputStream(android.net.Uri.parse(uriString))
            ?: throw IOException("Content resolver returned null stream for $uriString")
    }

    private suspend fun handleInboundText(
        chatImpl: RealFlashChatRepository,
        transferImpl: RealFlashTransferRepository,
        pairing: PairingCoordinator,
        calling: CallCoordinator,
        peerDeviceId: String,
        text: String,
    ) {
        // Calling signaling first — the most latency-sensitive frame class. Decode returns null
        // for non-call text (and unknown call actions), so chat/pairing fall through untouched.
        if (CallFrameCodec.decode(text) != null) {
            Log.i(TAG_WS, "Inbound call frame from id=$peerDeviceId")
            calling.onInboundText(peerDeviceId, text)
            return
        }
        // Group frames next: their prefixes (FLASH_GROUP/GMSG/GRCPT/GREAD/GSYNC/GMEDIA) are
        // disjoint from the direct chat families below, and the repository enforces trust +
        // membership itself.
        GroupFrameCodec.decode(text)?.let { frame ->
            Log.i(TAG_WS, "Inbound group frame ${frame.javaClass.simpleName} from id=$peerDeviceId")
            chatImpl.onInboundGroupWireFrame(peerDeviceId, frame)
            return
        }
        if (FlashTextFraming.parseFields(text, PAIR_PREFIX) != null) {
            Log.i(TAG_WS, "Inbound pairing frame from id=$peerDeviceId")
            pairing.onInbound(peerDeviceId, text)
            return
        }
        val msgFields = FlashTextFraming.parseFields(text, MSG_PREFIX)
        if (msgFields != null) {
            val localId = msgFields["localId"] ?: return
            chatImpl.onInboundWireFrame(
                MessageWireFrame.TextMessage(
                    localId = localId,
                    conversationId = msgFields["conversationId"] ?: "",
                    senderId = msgFields["senderId"] ?: "",
                    senderName = msgFields["senderName"] ?: "Peer",
                    sentAt = msgFields["sentAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
                    text = msgFields["text"] ?: "",
                    // Reply/quote metadata (#8); blank fields (non-reply / legacy peer) → null.
                    replyToId = msgFields["replyToId"]?.ifBlank { null },
                    replyToPreview = msgFields["replyToPreview"]?.ifBlank { null },
                ),
            )
            return
        }
        val receiptFields = FlashTextFraming.parseFields(text, RECEIPT_PREFIX)
        if (receiptFields != null) {
            chatImpl.onInboundWireFrame(
                MessageWireFrame.DeliveryReceipt(
                    messageId = receiptFields["messageId"] ?: return,
                    conversationId = receiptFields["conversationId"] ?: "",
                    memberId = receiptFields["memberId"] ?: "",
                    deliveredAt = receiptFields["deliveredAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
                ),
            )
            return
        }
        val readFields = FlashTextFraming.parseFields(text, READ_PREFIX)
        if (readFields != null) {
            chatImpl.onInboundWireFrame(
                MessageWireFrame.ReadReceipt(
                    conversationId = readFields["conversationId"] ?: "",
                    memberId = readFields["memberId"] ?: return,
                    upToMessageId = readFields["upToMessageId"] ?: return,
                    readAt = readFields["readAt"]?.toLongOrNull() ?: System.currentTimeMillis(),
                ),
            )
            return
        }
        val reactFields = FlashTextFraming.parseFields(text, REACT_PREFIX)
        if (reactFields != null) {
            chatImpl.onInboundWireFrame(
                MessageWireFrame.ReactionFrame(
                    messageId = reactFields["messageId"] ?: return,
                    conversationId = reactFields["conversationId"] ?: "",
                    memberId = reactFields["memberId"] ?: return,
                    emoji = reactFields["emoji"] ?: return,
                    isAdded = reactFields["isAdded"]?.toBooleanStrictOrNull() ?: true,
                ),
            )
            return
        }
        val typingFields = FlashTextFraming.parseFields(text, TYPING_PREFIX)
        if (typingFields != null) {
            chatImpl.onInboundWireFrame(
                MessageWireFrame.TypingFrame(
                    // Thread typing under the SENDER's device id, matching how inbound text is keyed
                    // (the wire conversationId is our own id from the peer's perspective).
                    conversationId = peerDeviceId,
                    memberId = typingFields["memberId"] ?: return,
                    memberName = typingFields["memberName"] ?: "Peer",
                    isTyping = typingFields["isTyping"]?.toBooleanStrictOrNull() ?: false,
                    timestampMs = typingFields["timestampMs"]?.toLongOrNull() ?: System.currentTimeMillis(),
                ),
            )
            return
        }
        val xferFields = FlashTextFraming.parseFields(text, XFER_PREFIX)
        if (xferFields != null) {
            val action = xferFields["action"] ?: return
            val transferId = xferFields["transferId"] ?: return
            transferImpl.onRemoteTransferControl(transferId, action)
            return
        }
        Log.w(TAG_CHAT, "Received unrecognized text frame (${text.length} chars)")
    }

    private fun handleInboundBinary(
        transferImpl: RealFlashTransferRepository,
        receivePipeline: ReceivePipeline,
        openHandles: ConcurrentHashMap<String, RandomAccessSinkHandle>,
        incomingMeta: ConcurrentHashMap<String, ChunkFrame.FileStart>,
        receivedPaths: ConcurrentHashMap<String, String>,
        incomingByPeer: ConcurrentHashMap<String, MutableSet<String>>,
        peerLabel: String,
        peerDeviceId: String?,
        data: ByteArray,
        reply: (ByteArray) -> Boolean,
        /**
         * Invoked once per inbound transfer when its file header arrives, so the chat layer can
         * mint an inbound attachment bubble (#1). Null for the data-channel router path, which has
         * no chat repo reference; the WS session collector supplies it.
         */
        onAttachmentStarted: ((peerDeviceId: String, transferId: String, fileName: String, totalBytes: Long) -> Unit)? = null,
    ) {
        Log.d(TAG_TRANSFER, "Received binary frame: ${data.size} bytes from $peerLabel")
        // 1. First route to active senders (ACKs or COMPLETE from receiver)
        if (transferImpl.onInboundFrame(data)) {
            Log.d(TAG_TRANSFER, "Inbound binary frame consumed by sender dispatcher")
            return
        }

        // 2. If not consumed by a sender, route to receiver pipeline
        val events = receivePipeline.onFrame(data)
        for (event in events) {
            when (event) {
                is ReceiveEvent.SessionStarted -> {
                    val frame = event.frame
                    incomingMeta[frame.transferId] = frame
                    // Register under the peer so a transport drop can fail this transfer (#4).
                    peerDeviceId?.let { pid ->
                        incomingByPeer.getOrPut(pid) {
                            java.util.Collections.newSetFromMap(ConcurrentHashMap())
                        }.add(frame.transferId)
                    }
                    // A re-offer of a transfer this device already accepted is a RETRY, not a new
                    // offer: the previous attempt's session was torn down with the transport (see
                    // cleanupInbound), so the sender's relaunch arrives as a fresh FILE_START and
                    // parks on the #5 acceptance gate with a deferred sink — every chunk dropped,
                    // no ACKs, the row frozen. The user already said yes, so resolve the sink
                    // immediately instead of prompting a second time. (Cancelled is excluded by
                    // isResumableInboundRetry: a declined offer is never auto-accepted.)
                    if (transferImpl.isResumableInboundRetry(frame.transferId)) {
                        val opened = receivePipeline.acceptSession(frame.transferId)
                        transferImpl.onIncomingStarted(
                            transferId = frame.transferId,
                            fileId = frame.fileId,
                            fileName = frame.fileName,
                            totalBytes = frame.totalBytes,
                            peerName = peerLabel,
                            peerDeviceId = peerDeviceId,
                            localPath = receivedPaths[frame.transferId],
                        )
                        Log.i(TAG_TRANSFER, "Re-offer of accepted transfer '${frame.fileName}' from $peerLabel — resuming (sinkResolved=$opened)")
                        continue
                    }
                    // #5: surface as a pending OFFER (Offered state, no sink/file, no chat bubble
                    // yet). Acceptance (incomingControl ACTION_ACCEPT) resolves the sink, flips it
                    // Transferring, mints the attachment bubble, and RESUMEs the parked sender.
                    transferImpl.onIncomingOffered(
                        transferId = frame.transferId,
                        fileId = frame.fileId,
                        fileName = frame.fileName,
                        totalBytes = frame.totalBytes,
                        peerName = peerLabel,
                        peerDeviceId = peerDeviceId,
                    )
                    // Bug 3: auto-download hook. AppEngine sets onIncomingOffer to accept the offer
                    // only when the file's MIME category is enabled in settings (voice/image default
                    // on; video/file default off). When null or policy says no, it stays Offered.
                    onIncomingOffer?.invoke(frame.transferId)
                    Log.i(TAG_TRANSFER, "Offered '${frame.fileName}' (${frame.totalBytes} bytes, ${frame.totalChunks} chunks) from $peerLabel — awaiting accept")
                }
                is ReceiveEvent.AckBatchReady -> {
                    Log.d(TAG_TRANSFER, "Receiver emitting ACK batch with ${event.frame.indexes.size} indexes")
                    // #20: persist the confirmed indexes so a post-restart resume skips them.
                    transferImpl.onIncomingChunkConfirmed(event.frame.transferId, event.frame.indexes)
                    updateIncomingProgress(transferImpl, receivePipeline, incomingMeta, event.frame.transferId)
                    reply(ChunkFrame.serialize(event.frame))
                }
                is ReceiveEvent.Completed -> {
                    val transferId = event.frame.transferId
                    val handle = openHandles.remove(transferId)
                    handle?.flush()
                    handle?.close()
                    incomingByPeer.values.forEach { it.remove(transferId) }
                    val path = receivedPaths.remove(transferId)
                    val expectedHex = incomingMeta.remove(transferId)?.fileSha256Hex
                    // #19: whole-file digest recheck against the manifest hash, layered on the
                    // pipeline's per-chunk verify-before-write. Chunk hashes already guarantee each
                    // piece's integrity; this catches assembly/offset faults or manifest/content
                    // divergence before the file is surfaced as trusted.
                    val wholeFileVerified = event.frame.verified && verifyWholeFile(path, expectedHex)
                    transferImpl.onIncomingCompleted(
                        transferId,
                        wholeFileVerified,
                        localPath = path,
                    )
                    Log.i(TAG_TRANSFER, "Receiver completed transferId=$transferId chunkVerified=${event.frame.verified} wholeFileVerified=$wholeFileVerified")
                    reply(ChunkFrame.serialize(event.frame))
                }
                is ReceiveEvent.Rejected -> {
                    // Late ACK/COMPLETE arriving after our own dispatcher resolved is benign
                    // noise on a symmetric mesh — debug level; everything else warns.
                    if (event.reason == com.transfer.flash.core.transfer.chunked.RejectReason.UNEXPECTED_DIRECTION) {
                        Log.d(TAG_TRANSFER, "Late/unmatched frame ignored: reason=UNEXPECTED_DIRECTION transferId=${event.transferId}")
                    } else {
                        Log.w(TAG_TRANSFER, "Receiver rejected chunk frame: reason=${event.reason} transferId=${event.transferId} index=${event.index}")
                    }
                }
            }
        }
    }

    /**
     * Transport-agnostic inbound ChunkFrame routing used by BOTH the WebSocket session collector
     * and the dedicated data-channel server (real multistream).
     */
    class DataChannelRouter internal constructor(
        private val receivePipeline: ReceivePipeline,
        private val openHandles: ConcurrentHashMap<String, RandomAccessSinkHandle>,
        private val incomingMeta: ConcurrentHashMap<String, ChunkFrame.FileStart>,
        private val receivedPaths: ConcurrentHashMap<String, String>,
        private val incomingByPeer: ConcurrentHashMap<String, MutableSet<String>>,
    ) {
        /** Late-bound because the repo is constructed after this router in ensureStarted. */
        @Volatile
        var transfer: RealFlashTransferRepository? = null

        fun onBytes(peerLabel: String, peerDeviceId: String?, bytes: ByteArray, reply: (ByteArray) -> Boolean) {
            val impl = transfer ?: return
            handleInboundBinary(impl, receivePipeline, openHandles, incomingMeta, receivedPaths, incomingByPeer, peerLabel, peerDeviceId, bytes, reply)
        }
    }

    /**
     * Streams the fully-assembled destination file through SHA-256 and compares it in constant time
     * against the manifest's declared whole-file digest (#19). Returns false when either input is
     * missing/invalid or the file cannot be read, so an unverifiable transfer surfaces as
     * unverified rather than being silently trusted.
     */
    private fun verifyWholeFile(path: String?, expectedHex: String?): Boolean {
        if (path.isNullOrBlank() || expectedHex.isNullOrBlank() || !Sha256.isValidHex(expectedHex)) {
            return false
        }
        return runCatching {
            val acc = IncrementalSha256()
            File(path).inputStream().use { input ->
                val buffer = ByteArray(64 * 1024)
                while (true) {
                    val read = input.read(buffer)
                    if (read < 0) break
                    acc.update(buffer, 0, read)
                }
            }
            Sha256.hexEqualsConstantTime(acc.digestHex(), Sha256.normalizeHex(expectedHex))
        }.getOrElse { e ->
            Log.w(TAG_TRANSFER, "Whole-file verify failed to read $path: ${e.message}")
            false
        }
    }

    /** Recomputes verified bytes for an inbound transfer from the pipeline's done-set. */
    private fun updateIncomingProgress(
        transferImpl: RealFlashTransferRepository,
        receivePipeline: ReceivePipeline,
        incomingMeta: ConcurrentHashMap<String, ChunkFrame.FileStart>,
        transferId: String,
    ) {
        val start = incomingMeta[transferId] ?: return
        val done = receivePipeline.doneIndexes(transferId) ?: return
        var bytes = 0L
        for (index in done) {
            bytes += minOf(start.chunkSize.toLong(), start.totalBytes - index.toLong() * start.chunkSize)
        }
        transferImpl.onIncomingProgress(transferId, bytes)
    }

    /** Strips anything that could escape the intended directory (path-traversal guard, AGENTS.md §19). */
    private fun sanitizePathComponent(raw: String): String =
        raw.replace(Regex("[^A-Za-z0-9._ ()-]"), "_").trim('.').ifBlank { "unnamed" }.take(120)

    /**
     * Best-effort MIME from a file name extension, used to render an inbound attachment bubble as
     * an image/video/audio card vs. a generic file card (#1). Falls back to octet-stream.
     */
    private fun guessMimeType(fileName: String): String {
        // Locale.ROOT, not getDefault(): the extension is machine data matched against the
        // lowercase ASCII literals below. Turkish getDefault() folds 'I' to dotless 'ı', which
        // would silently break "TIFF"/"GIF"/"MIDI". Same fix as core/engine Flash.kt.
        val ext = fileName.substringAfterLast('.', "").lowercase(Locale.ROOT)
        return when (ext) {
            "jpg", "jpeg" -> "image/jpeg"
            "png" -> "image/png"
            "gif" -> "image/gif"
            "webp" -> "image/webp"
            "heic", "heif" -> "image/heic"
            "bmp" -> "image/bmp"
            "mp4", "m4v" -> "video/mp4"
            "mov" -> "video/quicktime"
            "webm" -> "video/webm"
            "mkv" -> "video/x-matroska"
            "3gp" -> "video/3gpp"
            "mp3" -> "audio/mpeg"
            "m4a", "aac" -> "audio/aac"
            "ogg", "oga" -> "audio/ogg"
            "wav" -> "audio/wav"
            "opus" -> "audio/opus"
            "flac" -> "audio/flac"
            "pdf" -> "application/pdf"
            "zip" -> "application/zip"
            "txt" -> "text/plain"
            else -> "application/octet-stream"
        }
    }

    /**
     * Acquires the CPU + Wi-Fi power locks for the engine's lifetime. Idempotent: both locks are
     * non-reference-counted, and an already-held lock is left alone, so a second [ensureStarted]
     * (or a service restart) cannot stack acquisitions. See [wakeLock] / [wifiLock].
     */
    private fun acquirePowerLocks(context: Context) {
        if (wakeLock?.isHeld != true) {
            wakeLock = runCatching {
                context.getSystemService(PowerManager::class.java)
                    .newWakeLock(PowerManager.PARTIAL_WAKE_LOCK, WAKE_LOCK_TAG)
                    .apply {
                        setReferenceCounted(false)
                        acquire()
                    }
            }.onFailure { Log.w(TAG_WS, "Wake lock unavailable", it) }.getOrNull()
        }
        if (wifiLock?.isHeld != true) {
            val wifiMode = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                WifiManager.WIFI_MODE_FULL_LOW_LATENCY
            } else {
                @Suppress("DEPRECATION")
                WifiManager.WIFI_MODE_FULL_HIGH_PERF
            }
            wifiLock = runCatching {
                context.getSystemService(WifiManager::class.java)
                    .createWifiLock(wifiMode, WIFI_LOCK_TAG)
                    .apply {
                        setReferenceCounted(false)
                        acquire()
                    }
            }.onFailure { Log.w(TAG_WS, "Wi-Fi lock unavailable", it) }.getOrNull()
        }
        Log.i(TAG_WS, "Power locks held for mesh: wake=${wakeLock?.isHeld == true} wifi=${wifiLock?.isHeld == true}")
    }

    /** Releases both power locks. Only [stopAll] calls this — a stopping service must not. */
    private fun releasePowerLocks() {
        runCatching { wakeLock?.let { if (it.isHeld) it.release() } }
        wakeLock = null
        runCatching { wifiLock?.let { if (it.isHeld) it.release() } }
        wifiLock = null
    }

    /**
     * Registers the screen-on / user-present re-arm for the engine's lifetime. Idempotent: an
     * already-registered receiver is left alone, so a second [ensureStarted] (or a service restart)
     * cannot stack registrations. See [screenReceiver] for why this is not the service's job.
     */
    private fun registerScreenReceiver(context: Context) {
        if (screenReceiver != null) return
        val receiver = object : BroadcastReceiver() {
            override fun onReceive(context: Context?, intent: Intent?) {
                when (intent?.action) {
                    Intent.ACTION_SCREEN_ON, Intent.ACTION_USER_PRESENT -> {
                        Log.i(TAG_WS, "Screen-on (${intent.action}) — re-arming discovery + auto-connect")
                        onScreenOn()
                    }
                }
            }
        }
        val filter = IntentFilter().apply {
            addAction(Intent.ACTION_SCREEN_ON)
            addAction(Intent.ACTION_USER_PRESENT)
        }
        // NOT_EXPORTED: both actions are protected system broadcasts, and API 34+ requires an
        // explicit export flag for every runtime registration.
        runCatching { ContextCompat.registerReceiver(context, receiver, filter, ContextCompat.RECEIVER_NOT_EXPORTED) }
            .onSuccess { screenReceiver = receiver }
            .onFailure { Log.w(TAG_WS, "Screen-on receiver registration failed", it) }
    }

    /** Counterpart of [registerScreenReceiver]; only [stopAll] calls it. */
    private fun unregisterScreenReceiver() {
        val receiver = screenReceiver ?: return
        screenReceiver = null
        runCatching { appContextRef?.unregisterReceiver(receiver) }
    }

    /** Stops advertising/browsing, sessions, and releases the ephemeral port. Idempotent. */
    suspend fun stopAll() = lifecycleMutex.withLock {
        val currentEngine: CompositeDiscovery?
        val currentNetwork: WsFlashNetwork?
        synchronized(this) {
            currentEngine = composite
            currentNetwork = network
            composite = null
            network = null
            transferRepo = null
            chatRepo = null
            pairing = null
            callCoordinator = null
        }
        binderJob?.cancel()
        binderJob = null
        autoConnectJob?.cancel()
        autoConnectJob = null
        // Silence the ring before the scope dies: appScope.cancel() below kills the collector, so
        // nothing would ever deliver the stopping edge, and a MediaPlayer nobody holds keeps looping.
        callRingJob?.cancel()
        callRingJob = null
        callRinger?.stop()
        callRinger = null
        autoConnectGate = null
        localDeviceId = null
        dataServer?.stop()
        dataServer = null
        currentEngine?.stopAll()
        currentNetwork?.stop()
        // #16: cancel every collector/session job launched on appScope (incoming/outgoing control,
        // activeSessions, per-session readers, auto-connect). ensureStarted recreates the scope.
        appScope.cancel()
        // Nothing left to keep awake, and nothing left to re-arm: this is the only place the
        // engine's power locks are dropped and its screen-on receiver is torn down.
        unregisterScreenReceiver()
        releasePowerLocks()
        appContextRef = null
    }

    const val TOTAL_TEST_BYTES: Long = 10L * 1024 * 1024

    /** Cadence of the background auto-connect sweep; per-peer attempts are gated by [AutoConnectGate]. */
    private const val AUTO_CONNECT_SWEEP_MS = 5_000L

    private const val WAKE_LOCK_TAG = "flash:ws-mesh"
    private const val WIFI_LOCK_TAG = "flash:ws-mesh-wifi"
}

/**
 * Deterministic pseudo-random byte stream for transfer testing. Same seed => same bytes, so a
 * future end-to-end check can compare digests across devices without shipping a test file.
 */
class DeterministicPayloadInputStream(
    private val totalBytes: Long,
    private val seed: Long = 0x464C615348L,
) : InputStream() {

    private val rng = java.util.Random(seed)
    private val buffer = ByteArray(BUFFER_SIZE).also(rng::nextBytes)
    private var remaining: Long = totalBytes
    private var bufferPos: Int = BUFFER_SIZE

    override fun read(): Int {
        if (remaining <= 0) return -1
        if (bufferPos >= BUFFER_SIZE) {
            bufferPos = 0
        }
        remaining--
        return buffer[bufferPos++].toInt() and 0xFF
    }

    override fun read(b: ByteArray, off: Int, len: Int): Int {
        if (remaining <= 0) return -1
        if (bufferPos >= BUFFER_SIZE) bufferPos = 0
        val count = minOf(len.toLong(), remaining, (BUFFER_SIZE - bufferPos).toLong()).toInt()
        System.arraycopy(buffer, bufferPos, b, off, count)
        bufferPos += count
        remaining -= count
        return count
    }

    companion object {
        private const val BUFFER_SIZE = 64 * 1024
    }
}
